### ISSUE TITLE
Missing projection for DokanNtStatusFromWin32

### ISSUE THREAD

**Issue by d2dyno1** [dokan-dev/dokany#1041]
It would be very helpful if DokanNet provided `DokanNtStatusFromWin32()` out of the box. This helper function is unfortunately missing in DokanNet.

**Comment by Liryna** [comment]
@d2dyno1 Hi,
It was made on purpose to not directly include the function in dokannet to keep the wrapper as pure C# as possible.
That's why DokanResult was created to abstract the NtStatus values.
That said, you can still import the function with a dllimport directly in your code for your own usage.
