### ISSUE TITLE
[Request] callback-based API

### ISSUE THREAD

**Issue by Absolucy** [dokan-dev/dokany#1097]
Hi, I've been making a userspace filesystem library for Rust (planning to wrap both FUSE and Dokany - with the FUSE half pretty much done already), and I noticed one problem that's stopping me from doing the dokany side - lack of async support. I'm using the [low-level FUSE functions which have a "reply" callback](http://libfuse.github.io/doxygen/structfuse__lowlevel__ops.html), rather than synchronously using the return value from the function.

Is anything liked this planned or in the works for Dokany?

**Comment by Liryna** [comment]
Hi @Absolucy ,

There is a pull request opened just for that actually https://github.com/dokan-dev/dokany/pull/307
A large part of this pull request was merged. I am not planning to merge the remaining part (see my comment [here](https://github.com/dokan-dev/dokany/pull/307#issuecomment-1003815187)) but I am open to pull request!

**Comment by Absolucy** [comment]
I wish I knew enough about the Dokan codebase to contribute.

I mean, I guess I could learn and try when I have some free time, but no guarantees.

Out of curiosity, why not merge that part of the PR? The comment doesn't seem to explain the "why".

**Comment by Liryna** [comment]
The PR is a rewrite of the library with a lot of great ideas (memory pull / threading / ...) which are now merged and [took a lot of effort](https://github.com/dokan-dev/dokany/compare/v1.5.1.1000...v2.0.0.1000) to happen.
I did not merge the redesign of the new async API to avoid adding another layer of complexity while knowing there were still pending issues [1](https://github.com/dokan-dev/dokany/pull/307#issuecomment-300071950) [2]( https://github.com/dokan-dev/dokany/pull/307#issuecomment-257590762) and having an async API wasn't requested by the community since.

**Comment by Liryna** [comment]
@Absolucy Let me know if you need more details.
