### ISSUE TITLE
Switch installer from NSIS to WiX

### ISSUE THREAD

**Issue by Corillian** [dokan-dev/dokany#116]
I am working on packaging Dokan into the installer for my driver and I am running into a number of significant problems caused by how NSIS handles uninstallation. For starters uninstallation occurs in a separate executable which, while inconvenient, is surmountable. The bigger issue is that the uninstaller unpacks *another* executable that it runs for uninstallation and then exits before the child process completes. To make matters worse the child process has a garbage name and all this makes it extremely difficult to figure out if the child process has terminated successfully - especially if being run in silent mode. If we simply generate an MSI for Dokan all of these problems melt away.

WiX: http://wixtoolset.org/

**Comment by Liryna** [comment]
@Corillian I agree totally that we have to move to msi. But we are more focusing in the stability of dokany for now. 
This feature will only be available if someone make a pull request.

**Comment by Corillian** [comment]
I'll take care of it

**Comment by suy** [comment]
I am packaging my application with WiX (because other developer started it, I'm quite ignorant about it), and attempting to include Dokan in it was a *huge* challenge (at least for me; as said, maybe because the previous lack of knowledge).

I saw the source code for the current NSIS installer and I was very jealous: it's *very* simple in comparison.

If you manage to do it, you will receive my sincere thanks. :smile: If you do it in a way that can be reused for people who have to redistribute Dokan, even more! :heart:

**Comment by Liryna** [comment]
I just got a contribution by mail. I made a quick test and it seems to work.
I will continue the test and add it the repository for the 0.8.0 stable release.

**Comment by Liryna** [comment]
We prefer to add it in the next release 0.8.1

**Comment by js69** [comment]
See https://github.com/dokan-dev/dokany/pull/124

**Comment by Corillian** [comment]
Alrighty I just submitted my pull request (https://github.com/dokan-dev/dokany/pull/125). Currently the 3rd party dependencies are not included in that PR so it won't build. We need to figure out what we want to do with them. The options are:

1) I check them into the git repo, they're ~30mb in total size.
2) We upload them somewhere and the bootstrapper can actually download them when it runs

**Comment by suy** [comment]
Or 3: use [Git LFS](https://git-lfs.github.com/). It's supported on Github, and there are clients nicely installable on all platforms. It's an additional tool to install, though.

**Comment by Liryna** [comment]
Thank you @Corillian for your PR, I will try to check both PR this weekend.
Is it possible to make two installer like now ? (with & without redist embedded)
I am not a big fan that the installer would fail if the serveur is down.
Otherwise Git LFS would be not bad if there is a way to use it with WiX.

**Comment by Corillian** [comment]
I can make an installer, where would you like me to upload it? Also I've been investigating Git LFS and it doesn't seem to work particularly well. In fact it isn't working at all I just get:

```
Git LFS: (0 of 1 files) 0 B / 1.43 MB
Post https://github.com/Corillian/dokany.git/info/lfs/objects/batch: EOF
error: failed to push some refs to 'https://github.com/Corillian/dokany.git'
```

which isn't particularly helpful. On top of that by default a user only gets 1gb of storage and 1gb of bandwidth a month before they have to pay ~$4 a month which is a very low cap. Each exe is ~15mb or less so perhaps it's best if I just check it into the repo without LFS?

**Comment by Liryna** [comment]
Oh, I was not aware of the bandwidth limit :cry: 
Can we not just continue to copy the redist our self in the WiX folder ? 
And WiX will create one installer with and another wihtout redist.

**Comment by suy** [comment]
I wasn't aware of the hard limits. GitLab has a 10 GB limit, so I was spoiled by that. :(

@Corillian The error you were having maybe it's due to forks being restricted. At least I think that was the case a while ago. Since the files aren't that big, maybe checking them directly in Git is fast enough and doesn't slow the repo too much.

**Comment by js69** [comment]
Instead of adding any large redist to the repo I would add a "filecheck and download if necessary" step into the project, using e.g. the wget command from here:

https://eternallybored.org/misc/wget/

Commands for the VC 2015 SP1 Redists:

wget https://download.microsoft.com/download/C/E/5/CE514EAE-78A8-4381-86E8-29108D78DBD4/VC_redist.x86.exe
wget https://download.microsoft.com/download/C/E/5/CE514EAE-78A8-4381-86E8-29108D78DBD4/VC_redist.x64.exe

**Comment by Corillian** [comment]
Burn already comes with the ability to download dependencies on demand (http://wixtoolset.org/documentation/manual/v3/xsd/wix/remotepayload.html). My concern is that if Microsoft ever changes the URL, which they do from time to time, it would break the installer which is why I had suggested previously that we host the dependencies ourselves or embed them into the installer. Also it should be noted that installing dependencies via custom actions is considered bad practice which is the whole reason WiX includes the Burn bootstrapper framework in the first place (which is what Microsoft uses for many of their installers btw).

**Comment by js69** [comment]
The project will download the Redists only so the WiX compilation will work (WiX compares the hash of the file present during build time with the one the Setup via Burn will download during runtime).

The VC runtime download URLs in the Bundle can only be updated when new versions have been released as Microsoft does not provide working, stable URLs for the "always latest and current" version. LinkIds by Microsoft are extremely unreliable as I had to learn. Linkids also deliver a HTTP return code that is filtered or misinterpreted by many proxies/firewalls and generally doesn't work well with Burns download method..

Not sure where you get the idea custom actions are used to install dependencies. Prerequisites are installed by the Bootstrapper via Burn. 

Also, your Bundle includes a ExePackage for NetFx which I think should simply be replaced by using the NetFxExtension with <WixVariable Id="WixMbaPrereqPackageId" Value="NetFx46Web" />

**Comment by Corillian** [comment]
NetFx doesn't support .net 4.6.1 yet (http://wixtoolset.org/issues/4976/). As soon as it does the bootstrapper can be updated accordingly. Are you suggesting that executing wget wouldn't be via a custom action?

**Comment by js69** [comment]
The wget commands would be added in the Pre-Build Event of the Bootstrapper project.

What component exactly would need NET 4.6.1? I'd guess your Bootstrappper-DLL should work  with 4.0, right?

**Comment by Corillian** [comment]
Ah ok, I misunderstood the context of when we would be using wget. That's a good idea and probably the best solution outside of keeping the files in git. May I suggest we use MSBuild instead? The MSBuild extension pack already includes an extension for downloading a file called MSBuild.ExtensionPack.Web.WebClient: http://www.msbuildextensionpack.com/help/4.0.12.0/index.html

I don't believe I'm using any C# 6 syntax or any other .NET 4.6.1 specific features though .NET 4.6.1 includes a number of low level enhancements for WPF. I don't really see the need for downgrading it just to use an existing NetFX extension when 4.6.1 will be supported soon however I doubt it would be an issue.

**Comment by js69** [comment]
I have integrated the difx and ServiceInstall to install driver and mounter. My MSI still executes dokanctl /i n to install network provider (not sure if that is necessary, how can I test if network provider is really active?).

For signing there is a sample post build event added with:

if /I "$(ConfigurationName)" == "Release" signtool.exe sign /fd SHA256 /tr http://timestamp.geotrust.com/tsa /td SHA256 /f certificate.pfx /p PASSWORD "$(TargetDir)$(TargetFileName)"

Replace signtool.exe, certificate and password according to your own settings.

It's important to use the SHA256 digest (for timestamp as well) because SHA1 will be deprecated.

The same step should be used to sign the drivers and DLLs (for the drivers instead of using the builtin signing step as it doesn't allow the timestamp parameter).

**Comment by Liryna** [comment]
Oh great ! I will test it the sooner as I can!
You can test the network provider by running `mirror.exe /n /r C:\Users /l m` (/n network provider)

**Comment by js69** [comment]
Liryna, I am still not sure what the Network provider is supposed to actually implement. 

Is it supposedly possible to create a network share for a virtual drive and actually access files on that share? If so, how?

**Comment by Liryna** [comment]
I am not sure that I understood correctly your question.

Mounting your dokan device as network device is only an option. You don't need to implement something.
People use this option because the behaviour of the read/write are different and also better when your implementation access network data.

I have never try to acces it from another computer so I cannot say...

Also cince 1.0.0, there is also an new option `mirror.exe /n /r C:\Users /l m /n /u \localhost\users` -> Win + R: `\\localhost\users\js69` will open in explorer C:\Users\js69

**Comment by js69** [comment]
Well, mounting without /n option allows to create a share for the virtual drive. The files on the share cannot be accessed though.I guess the implementation for sharing does not exist.

/u option files only show with cmd.exe, e.g. "dir \\localhost\users". Opening thatpath in Explorer does not work on my Win10 VM.

**Comment by Liryna** [comment]
There is a 'bug' for now on Win10, try to acces with the subfolder directly `\\localhost\users\myuser`

**Comment by Liryna** [comment]
WiX installer has been added to the repository https://github.com/dokan-dev/dokany/commit/943a5d5c6551bc5085317c50d975bd8db55e73ac

Thanks to all of you for the help & contribution !
