### ISSUE TITLE
Unmount() callback is not executed

### ISSUE THREAD

**Issue by accorp** [dokan-dev/dokany#117]
It can be checked with mirror sample. There is MirrorUnmount() set to print debug message:
```
DbgPrint(L"Unmount\n"); 
```

```
console_1> mirror.exe /r c:\test /l p /d /s
console_2> dokanctl.exe /u p
```

Debug output:
```
...

###Cleanup 0004
Cleanup: c:\test\

###Close 0004
Close: c:\test\

ReturnedLength 0
Ioctl failed for wait with code 55.
Thread will be terminated
ReturnedLength 0
Ioctl failed for wait with code 55.
Thread will be terminated
ReturnedLength 0
ReturnedLength 0
ReturnedLength 0
Ioctl failed for wait with code 55.
Thread will be terminated
Ioctl failed for wait with code 55.
Thread will be terminated
Ioctl failed for wait with code 55.
Thread will be terminated

unload
Success
```

Maybe there is no need in Unmount() callback - this event can be handled after DokanMain()'s return.
But there is no way to handle mount event, because call to DokanMain() is blocking.
I suggest to replace Unmount() callback with Mount() to be called after successful mount.

**Comment by Liryna** [comment]
Hi @accorp ,

You are right, Unmount is never called for now but it is better to keep it in case we handle it in the futur.
Mount() could be add and call before operations starts but it would be the same as you calling it before DokanMain().
I mean that if dokan call you during the initialization of your device, it doesn't mean that the mount has been successful since there is still some job to do (like starting the operations for examples).

**Comment by suy** [comment]
FWIW, I've experienced a bug with OSXFUSE where fuse_loop/fuse_main block (as DokanMain does) but the file system is not mounted. Since the normal behaviour is "only a non-zero return value is error" means my application can't determine that there is an error to report it, or restart the file system. :disappointed:  If fuse had the reverse of `destroy`, it could provide a notification of the FS being ready at that point, so I think it could be useful in Dokan too.

Since Dokan 0.8 will break binary compatibility, I would add the callback, even if it doesn't do anything yet, so in the future can do it without breaking it.

**Comment by accorp** [comment]
Hello @Liryna

To implement Mount() my assumption was to call it direct from DokanMain():
{
  * open device, return error if failed
  * call DokanStart(), return error if failed
  * call DokanMount(), return error if failed  
[ At this point there is no way for DokanMain() to return value other than DOKAN_SUCCESS, so here we can ]
  * call Mount()
  * start threads
  * wait for threads
  * return DOKAN_SUCCESS

}

Like this accorp/dokany@85922da2ad697f90c35298997d9e4342d7de0ef1. Am I missing something?

**Comment by Liryna** [comment]
@accorp , I have not seen that DokanMain do not check _beginthreadex ><
So you are right! we can do it :smiley: 

Could you create a pull request with your changes ? :heart: 

@suy , I have never used dokan_fuse myself :( I am sorry, I cannot help you for it

**Comment by Liryna** [comment]
https://github.com/dokan-dev/dokany/pull/121
About Unmount not called, @Maxhy , do you think that mountmanager would fix it ? (getting proper IRP when disk is unmount/eject).

**Comment by Maxhy** [comment]
Well I don't think so. I think here the problem is more an inconsistent call to Unmount user-mode callback function.
Right now it is only called in case of IRP_MJ_SHUTDOWN if I'm correct.

**Comment by Liryna** [comment]
Ok, so I imagine we could just call Unmount here:
https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.c#L247

**Comment by suy** [comment]
El Sunday 06 December 2015, Liryna escribió:
> @suy , I have never used dokan_fuse myself :( I am sorry, I cannot help you
> for it

Oh, no need to. I was mentioning an issue I experienced with OSXFUSE directly, 
so not Dokan related at all. Just a proof that, IMHO, the FUSE API has an 
important flaw (that thankfully is now addressed in #121 in Dokan!).

**Comment by Liryna** [comment]
@accorp , I have made a new RC with Unmounted call when device is removed & also renamed mount to mounted. Can you try it and share your feelings about it ?
https://github.com/dokan-dev/dokany/releases/tag/v0.8.0-RC4

**Comment by accorp** [comment]
@Liryna
Thanks for your work, Mounted() and Unmounted() behaves as expected :yum:
Since 0.8.0 is binary incompatible with all previous versions, I think DokanMain() should return some error in case it gets DokanOptions.Version less than 800 to prevent old programs from silent crashes.
See #122
