### ISSUE TITLE
Open read-only file with FILE_FLAG_DELETE_ON_CLOSE flag

### ISSUE THREAD

**Issue by denisovpi** [dokan-dev/dokany#1255]
# Environment
 * Windows version: Win11 Pro 23H2
 * Processor architecture: x86-64
 * Dokany version: v2.2.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

I'm working on implementing our own file system. I took **dokan_memfs** as an example. The file creation function has two checks for specific conditions:
* Cannot delete a file with readonly attributes.
https://github.com/dokan-dev/dokany/blob/2165b60789ef1cdb02cf1c7e5743bfbbcc46449d/samples/dokan_memfs/memfs_operations.cpp#L134-L138

* Cannot open a readonly file for writing.
https://github.com/dokan-dev/dokany/blob/2165b60789ef1cdb02cf1c7e5743bfbbcc46449d/samples/dokan_memfs/memfs_operations.cpp#L140-L145

I noticed that if I change the order of these two conditions, the code will no longer pass the tests. This also happened with the implementation of the [dokan-rust-memfs](https://github.com/dokan-dev/dokan-rust/tree/master/dokan/examples/memfs). I created an [issue](https://github.com/dokan-dev/dokan-rust/issues/16).
I think that the implementation of external file systems should not affect the logic of the Dokany itself. This is a bug or this case should be described in the documentation or in the code example itself.

**Tests for [winfstest](https://github.com/Liryna/winfstest)**

`expect("CreateDirectory %s 0" % name, 0)`
`expect("CreateFile %s\\f GENERIC_WRITE 0 0 CREATE_ALWAYS FILE_ATTRIBUTE_READONLY 0" % name, 0)`
`expect("CreateFile %s\\f GENERIC_WRITE 0 0 OPEN_EXISTING FILE_FLAG_DELETE_ON_CLOSE 0" % name, "ERROR_ACCESS_DENIED")`

Output:
`not ok 3 - expect "CreateFile M:\81981b9e\f GENERIC_WRITE 0 0 OPEN_EXISTING FILE_FLAG_DELETE_ON_CLOSE 0" ERROR_ACCESS_DENIED - got 0`

**Comment by Liryna** [comment]
Hi @denisovpi ,

Thanks for pointing that out!
The test is failing because `STATUS_ACCESS_DENIED` triggers the library to check if the parent allows the deletion (normal Windows behavior).
https://github.com/dokan-dev/dokany/blob/2165b60789ef1cdb02cf1c7e5743bfbbcc46449d/dokan/create.c#L250-L254

I agree that the order shouldn't affect the behavior but the rule is actually to return the most precise and correct status for the operation. `STATUS_CANNOT_DELETE` is more precise type of error than `STATUS_ACCESS_DENIED`. The [documentation](https://github.com/dokan-dev/dokany/blob/master/documentations/mainpage.md?plain=1#L37) isn't clear about that but does say to return the proper value.
How do you think we should improve it ?

**Comment by denisovpi** [comment]
Hi, @Liryna,
I can't tell if something needs to be changed, but I agree that the code should return the most correct status.
I'll create a PR to fix the [dokan-rust-memfs](https://github.com/dokan-dev/dokan-rust/issues/16) and add the test to the [winfstest](https://github.com/Liryna/winfstest).
Thanks for your help.

**Comment by Liryna** [comment]
Thanks @denisovpi ! Please ping me on te rust PR 👍 I will be glad to review it
