### ISSUE TITLE
BSOD DokanStopEventNotificationThreadInternal

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#133]
Hello @marinkobabic ,

Sorry to ping you but I need some help on a part of the code.

It can happen that there is a BSOD in the queued fonction `DokanStopEventNotificationThreadInternal`.
https://github.com/dokan-dev/dokany/blob/master/sys/notification.c#L402 - PAGE_FAULT_IN_NONPAGED_AREA

I think it is because `Dcb` has been free by DokanDeleteDeviceObject https://github.com/dokan-dev/dokany/blob/master/sys/notification.c#L463
(DokanStopEventNotificationThreadInternal was queued too long and DokanDeleteDeviceObject had the time to be done in the main thread)

What do you think about it ?

**Comment by marinkobabic** [comment]
Hi Liryna

Yes. You are right!

The original idea was to execute DokanStopEventNotificationThread and to wait until the NotificationThread is terminated and then to delete the device. So I think we should go back to this original idea and keep it like it was before my change. This original approach was from my point of view correct.

Why I have changed the code: Sometimes the KeWaitForSingleObject hanged and this caused a BSOD and I wanted a simple workaround.

Now it's time to identify why this happens. Please add the following line in the DokanStopEventNotificationThread 

ASSERT(KeGetCurrentIrql() <= APC_LEVEL);

so that we can ensure that this is not the issue https://msdn.microsoft.com/en-us/library/windows/hardware/ff553350(v=vs.85).aspx.

Just to let you know. I have only been able to reproduce the issue when working with multiple dokan devices at the same time.

**Comment by Liryna** [comment]
Ok perfect !

So I have restore the old DokanStopEventNotificationThread and added the `ASSERT(KeGetCurrentIrql() <= APC_LEVEL);`.
After a couple of mount / unmount, the condition seems to be alright. No bsod made by the assert.

**Comment by marinkobabic** [comment]
Another question: Did you ever face the problem that when using keep alive and the mount had some dekay the driver deleted the device because of time out?

You had some talks about mounted and unmounted events. I think in generally that creating of device and mounting/unmountig should be separated in two steps. This way those two events make sense. I also do not like the behavior that the thread is blocked when doing a mount. In .net because of this fact the mounting must happen in a background thread. What are your thoughts?

**Comment by Liryna** [comment]
Never had this behaviour :open_mouth: Now that you say it, I agree that it can be possible but it also mean that you have a very slow computer.

For me, it is not a problem that having dokan that block all the time that it is mount. But If we can make it easily non-blocking, I am not against it.

**Comment by Liryna** [comment]
@marinkobabic , I have restore old code for now https://github.com/dokan-dev/dokany/commit/b458284013bc8262d18ef98bef80e8ea27c3b76b
Do you still think there is a possibility of BSOD with this code ?

**Comment by marinkobabic** [comment]
I'm missing the ASSERT statement I sent you last time. Please also add log 

Waiting for Notify thread to terminate
KeWaitForSingleObject
Notify thread successfully terminated.

In a special case I'm expecting that the ASSERT statement will be raised. The second option is that NotificationLoop causes a deadlock and therefore the method above hangs. Please add also some more log inside of NotificationLoop after SpinLock.

Thanks
Marinko

**Comment by marinkobabic** [comment]
The following line seems to be redundant

https://github.com/dokan-dev/dokany/blob/c4a0ae2c8620cdbeeb4c6b0297e983d4eb7a711a/sys/event.c#L360

Please check before removing.

**Comment by Liryna** [comment]
Ok I will do that !

Does DokanStopCheckThread should also be restore ?

**Comment by marinkobabic** [comment]
Hi Liryna

Here you can also restore the previous version. Please also add the same assert to ensure that we are running at correct IRQL. 

Thanks
Marinko

**Comment by Liryna** [comment]
Done: https://github.com/dokan-dev/dokany/commit/f1312b70d8f705836ee6046d3d006a9f1d36d208

**Comment by marinkobabic** [comment]
Great, thanks :smile:
