### ISSUE TITLE
CreateFile Failed \\.\Dokan1: 2

### ISSUE THREAD

**Issue by Driim** [dokan-dev/dokany#158]
Me again))))

I finally ported [Encfs4Win](https://github.com/Driim/WinEncFS/tree/dokany_0.8.0) to Dokany 0.8.0 and it work. But 0.8.0 have problem with deleting files and folder, so i tried to work with 1.0.0 beta1 and had this problem.

Just to checkout work of #130 I backports it to [0.8.0 version](https://github.com/Driim/dokany) and it work perfectly!
![dokany](https://cloud.githubusercontent.com/assets/1021338/12816568/39a97302-cb5e-11e5-8f82-c3ff3d173e0c.png)

**Comment by Liryna** [comment]
Hi back :smiley: 

Do you mean without https://github.com/dokan-dev/dokany/pull/130 it work ?

My knowledge with fuse are limited so if you could take a look :cry:

**Comment by Driim** [comment]
No, I mean i took #130 and patch v0.8.0 and it works, so problem not in this patch.

**Comment by Liryna** [comment]
Oh ! haha ok I understood now :smile: 

We have change the dokan driver name after 1.0.0-BETA1.
So the error you have is because it try to use `\\.\Dokan1` device but you have `\\.\Dokan` device installed.

I think you should continue with 0.8.0 + patch to not mix version in your system.
Your issue is going to be fixed by himself next release :smiley:
