### ISSUE TITLE
Review Oplock implementation

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#165]
During `IRP_MN_USER_FS_REQUEST` the system request different oplock.
Dokan have hack/fix for now, but it should be review and probably rewrite.

This will fix different issues like opening PDF.

https://msdn.microsoft.com/en-us/library/windows/hardware/ff547373%28v=vs.85%29.aspx

**Comment by marinkobabic** [comment]
Oplocks are support for directories and files. During the DokanDispatchCreate the parameter FILE_OPEN_REQUIRING_OPLOCK is passed. This is what happens in case of pdf, but it's not considered by dokan.

**Comment by Maxhy** [comment]
I'm doing few tests about oplock support, a little bit more complicated than excepted as share access and file lock/unlock is also badly implemented. I will take the opportunity to implement correctly shared access in the same time, please don't be in a hurry :smile:.
But I'm wondering if current Lock/Unlock operation exposed to user mode is really useful. Anyone using it correctly on user mode right now? Shouldn't this be managed transparently by the driver (= removing lock/unlock operation callbacks from user mode)?

**Comment by marinkobabic** [comment]
I think a callback method IsLocked should be enough. Here the scenario:

Machine A works on File1 islocked returns false
Machine B user opens File1 islocked returns true from usermode.

So the file can't be modified on machine B

**Comment by marinkobabic** [comment]
In generally it makes sense to do some prototyping to get the pdf issue work before doing a clean implementation. The actual situation is that operating system even does not read the file. The reads you may see are from windows defender which can be disabled using group policy. If during the creation Oplock fails a second request for Oplock will be made. In dokan is this always the case because we must return STATUS_PENDING and we complete the request later. 

FsRtlOplockFsctrl seems in some cases to complete the Irp, so dokan should not complete it self, see fastfat implementation.

Oplock is also a property of the advanced header. Depending on windows dk different property is needed. Please se the following macro:

#if (NTDDI_VERSION >= NTDDI_WIN8)

#define DokanGetFcbOplock(F)  &(F)->AdvancedHeader.Oplock

#else

#define FatGetFcbOplock(F)  &(F)->Oplock

#endif

I'm not sure if our problems are related to Oplock or not. We need to investigate and solve it. Maybe the edge browser will then also be able to open the pdf.

Please just post here as soon as you have more information.

**Comment by Maxhy** [comment]
I agree with your remarks about Win8 OS check and FsRtlOplockFsctrl. In fact I did some test work yesterday based on FastFat, see https://github.com/dokan-dev/dokany/tree/oplock branch. Far for complete / being tested.
I'm basing oplock counter check on Fcb->FileCount whereas a new UncleanCount counter should be used, but it will do the trick for now.
I think https://github.com/dokan-dev/dokany/blob/9eda5f0272992f2f585a6e177ca3048862ebc775/sys/fscontrol.c#L126 cannot be handled correctly as long as file Lock/Unlock is managed user-mode and I don't see any value to do it user-mode, but I could be wrong. I'm not sure to understand your `IsLocked` routine suggestion, in which case would it be used?

Also about PDF Edge reader issue, not sure it is related to Oplock. CdFs doesn't support FILE_OPEN_REQUIRING_OPLOCK on IRP_MJ_CREATE for instance.

**Comment by marinkobabic** [comment]
The IsLocked should be used to tell Office that the document should be opened write protected (SharedAccessViolation). Only the user mode application knows if somebody else is working on the same document on another machine. 

Just try the example above with machine A and machine B using onedrive and you will know what I'm talking about. 

It's not a must to handle the Oplock during open. Os will do a separate request for Oplock if you don't handle it in open case.

I'm actually just wondering why the document can't be opened. The only difference I actually see is the size on disk is different compared to Fat and Ntfs. Actually no idea what is there going on.

**Comment by marinkobabic** [comment]
In generally I think you can remove Lock/Unlock from code and handle all inside of the driver. The example I gave above can also now be supported, because we propagate the NTSTATUS to usermode. The application can return during the Open the SharedAccessViolation and the job is done. Just go on and make your life simpler to reach the target :smile: . There are actually no benefits by using Lock/Unlock.

**Comment by Maxhy** [comment]
Ok that was also my thoughts, good to know you share it :wink:. I will deprecate Lock/Unlock operations on user mode library and implement it in driver then. Let's wait for more feedback a few days in case someone would like to express a different opinion.

**Comment by Maxhy** [comment]
Current implementation with latest commits on `oplock` branch should be stable enough and even fix #154 according to my tests.
I will gladly wait for your tests @marinkobabic, thanks!

**Comment by Liryna** [comment]
@Maxhy There is some issue with the oplock branch at the mount and unmount.
When mounting from an admin cmd.exe, the device is not visible (like with the `/s` option).
This is probably related of MountGlobally that has been moved. https://github.com/dokan-dev/dokany/compare/master...oplock#diff-8c36b3beeaf36d353d6fa5cfa7eb5f6eL892

Also when I unmount, the device is still in explorer but inaccesible. Therefore it is impossible to mount with the same letter `Can't assign a drive letter`.

**Comment by Liryna** [comment]
@Maxhy mount issue has been correctly fixed Ty !
But copie past a file don't work anymore :cry:

**Comment by Liryna** [comment]
I wanted to copy `df.txt`
Mirror logs: http://pastebin.com/FYxqqe7K

Since every createFile return success, I would say it is one of the `FSCTL_OPLOCK` that fail

**Comment by Maxhy** [comment]
Fixed and I just merged oplock branch to master.
Thanks for discussions, inputs and feedbacks @marinkobabic @Liryna.
