### ISSUE TITLE
Cygwin/msys2 build optional

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#192]
@js69: Uhm, could you please make the cygwin/msys2/whatever gcc parts optional? Setting up the build environment for that is a pain and has zero value for non-Fuse Dokan development.

**Comment by Liryna** [comment]
If it is not build, WiX will fail.
Is it possible to make the files optional for WiX ?

**Comment by js69** [comment]
Yes, that is possible, some work with preprocessor and creating new fragments. 

The question is: why put the (from my point of view) unnecessary, esoteric cygwin stuff into the build and setup at all and not just create a separate build bat file/zip file of the binaries so that people who need it can build/get it? 

I'm going insane just trying to install all required packages for msys2 as it isn't documented.

**Comment by Liryna** [comment]
Build is now disabled if cygwin not installed: https://github.com/dokan-dev/dokany/commit/71301f46b5a555632ef4beaeaefeb93d94cfddbc

I would prefere that if WiX does not find the files because they was not build, he skip them. It would be more easy to maintaint that another installer/zip.

I will update the build documentation when we will make the final release. Otherwise there is the appveyor that already have all informations to create the environement.

**Comment by js69** [comment]
See https://github.com/js69/dokany/commit/b6db600e658073b850862b1f19f949e9e88d4a1d for wxs files and option to disable cygwin. WiX itself can't really file existence checks, it should be done by the build batch.

**Comment by Liryna** [comment]
That can be a solution !

I will take a look and will probably set "BuildCygwin" from the build install script.

Thank you @js69 !

**Comment by Liryna** [comment]
@js69 I have include your patch in the repository https://github.com/dokan-dev/dokany/commit/5ee8e215b04525abc0f759994354d8f0aeb95bff

Thank you again for your contribution :smiley:
