### ISSUE TITLE
Buffer is accessed out of bounds

### ISSUE THREAD

**Issue by x1596357** [dokan-dev/dokany#204]
# Environment
 * Windows version:  Windows 10 x64 10586.164
 * Processor architecture:  x64
 * Dokany version: https://github.com/dokan-dev/dokany/commit/a415ea952adadf6ce9635e75df7e7a2f34e08f62
 * Library type (Dokany/FUSE):  Dokany
 
# Check List
  - [* ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [* ] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [* ] I can always reproduce the issue with the provided description below.
  - [* ] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
 
In sys\volume.c#L171, 
`  RtlCopyMemory(FsAttrInfo->FileSystemName, L"Dokan\0", 10);`
However, FsAttrInfo is of type:
```
typedef struct _FILE_FS_ATTRIBUTE_INFORMATION {
  ULONG FileSystemAttributes;
  LONG MaximumComponentNameLength;
  ULONG FileSystemNameLength;
  WCHAR FileSystemName[1];
} FILE_FS_ATTRIBUTE_INFORMATION, *PFILE_FS_ATTRIBUTE_INFORMATION;
```
where FileSystemName is an array of WCHAR of length 1, isn't this access out of bound?
Same access made in sys\volume.c#L246.

**Comment by Maxhy** [comment]
The problem is not FileSystemName[1], this is a common way to have dynamic structure size on Windows kernel. Structure size is checked at https://github.com/dokan-dev/dokany/blob/master/sys/volume.c#L165 and if too small, a bigger memory should be allocated thanks to FsAttrInfo->FileSystemNameLength and STATUS_BUFFER_OVERFLOW.

Problem is that this is wrongly done (checking for 8 bytes whereas copying 10, using null-terminal string whereas it is not excepted, having FileSystemName set to Dokan instead of default NTFS as changed recently on other places/samples). @marinkobabic those was your changes, I believe it's a mistake? I'm gonna fix it later today.

**Comment by Liryna** [comment]
Hi @x1596357 ,

See microsoft samples: https://github.com/Microsoft/Windows-driver-samples/blob/97cf8edcaddff4fdbc5cc48d56b7d7eb2c39b749/filesys/cdfs/volinfo.c#L522 https://github.com/Microsoft/Windows-driver-samples/blob/97cf8edcaddff4fdbc5cc48d56b7d7eb2c39b749/filesys/fastfat/volinfo.c#L879

**Comment by x1596357** [comment]
Well, this dynamic structure size mechanism is new to me and I thought it was a bug. Obviously I have much to learn, thanks for the help.
