### ISSUE TITLE
Dokan Installer Detected as Containing Trojan

### ISSUE THREAD

**Issue by smoogle** [dokan-dev/dokany#213]
# Environment
 * Dokany version: 0.8.0 / 1.0.0-RC2
 
# Description

The Dokany installer is detected as containing a trojan;

For 1.0.0-RC2 [DokanSetup.exe]: https://www.virustotal.com/en/file/8b2a1ede9749fb5b3ea40c2a5824db463937435cc01eb5184733591d953d3462/analysis/

For 0.8.0 [DokanInstall_0.8.0.exe]:
https://www.virustotal.com/en/file/b74e185dd5ea41ca88c77b814fd2bd2c101ee23454ea96641c01a4b6229a50af/analysis/

Note there is no overlap in analyses, however the same trojan "Shelma" is detected in both.

**Comment by Liryna** [comment]
Hi @smoogle ,

Thank you for reporting it !

But thats obviously a false positive since only one antiviruse found the Shelma.

It seems like even plex have the same false positive: https://forums.plex.tv/discussion/211769/trojan-shelma-detected-in-pms-exe

Moreover I made an analyse with the installer that directly embedded the redist:
https://www.virustotal.com/en/file/83b19edde7c9dc5106dc0325d36ffb342ac8bd28669c9bcc8161cf688ed8de8e/analysis/

I think the false positive is made because the installer will try to download something remote (the redist) during install.

If you have another idea about it, feel free to propose it !

**Comment by smoogle** [comment]
I think you're right, but it might be worthwhile following up to see it can be whitelisted somehow - as some business will refuse to install it given these results.

**Comment by js69** [comment]
Yandex obviously doesn't do a good job of detecting widely used executable wrappers like WiX Burn in this case. You could try to contact them and point this out but in my experience antivirus companies are not very responsive or fast fixing false positives.

**Comment by Liryna** [comment]
Yandex use Sophos and his own internal antivirus for scanning websites. There is no desktop version of his antivirus.
Also Sophos does not detect dokan as virus, so I even think they will see that it is a false positive if they want to flag the download page.

And like @js69 said, It is going to be long before having an answer.

This issue was a good report and good to know but for now we are facing no problem.
