### ISSUE TITLE
dokan release(0.8, 1.0rc1, 1.0rc2) cant start dokan1 service

### ISSUE THREAD

**Issue by gang929** [dokan-dev/dokany#224]
# Environment
 * Windows version:  window 7
 * Processor architecture:  x64
 * Dokany version: 1.0 rc2, 1.0 rc1 0.8
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [Y ] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [ Y] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [Y ] I can always reproduce the issue with the provided description below.
  - [Y] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

# Description
No matter whether they are installed, or 0.8 1.0 rc2/rc1 version, being unable to mount mirror.exe, restart the computer always cant mount, after checked, is due to dokan1 service did not start.

sc query dokan1, show driver has invalid signature

# Logs
Please attach in separate files: mirror output, library logs and kernel [logs](https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan).
In case of BSOD, please attach minidump or dump analyze output.

**Comment by marinkobabic** [comment]
Please install all Windows Updates and reinstall dokan.


Von Samsung Mobile gesendet


-------- Ursprüngliche Nachricht --------
Von: gang929
Datum:05.05.2016 14:37 (GMT+01:00)
An: dokan-dev/dokany
Betreff: [dokan-dev/dokany] dokan release(0.8, 1.0rc1, 1.0rc2) cant start dokan1 service (#224)

Environment

  *   Windows version: window 7
  *   Processor architecture: x64
  *   Dokany version: 1.0 rc2, 1.0 rc1 0.8
  *   Library type (Dokany/FUSE): dokany

Check List

  *   [Y ] I checked my issue doesn't exist yet<https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue>
  *   [ Y] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  *   [Y ] I can always reproduce the issue with the provided description below.
  *   [Y] I have updated Dokany to the latest version (https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.

Description

No matter whether they are installed, or 0.8 1.0 rc2/rc1 version, being unable to mount mirror.exe, restart the computer always cant mount, after checked, is due to dokan1 service did not start.

sc query dokan1, show driver has invalid signature

Logs

Please attach in separate files: mirror output, library logs and kernel logs<https://github.com/dokan-dev/dokany/wiki/How-to-Debug-Dokan>.
In case of BSOD, please attach minidump or dump analyze output.

-

**Comment by gang929** [comment]
all windows updates?  can you point out which specifi update ?

**Comment by Liryna** [comment]
Related issue: https://github.com/dokan-dev/dokany/issues/187
