### ISSUE TITLE
Facilitate side-by-side installation of many products

### ISSUE THREAD

**Issue by andysyncplicity** [dokan-dev/dokany#227]
# Description

I'm currently investigating installation scenarios with Dokany. An interesting problem is: What happens when multiple products use Dokany? How do they install and uninstall cleanly?

For example, if the user installs three products that use Dokany, and then uninstalls one product, how does its installer know to leave Dokany behind?

This can create problems. For example, a hypothetical product, "AndyDrive," might have a requirement that uninstalling removes all components, drivers, ect, without impacting other installed software.

One approach, for a hypothetical product named "AndyDrive," is:

1. Recompile Dokany with different arguments, so certain constants change.
2. Sign a version of "AndyDokany" built from the same source code as Dokany. (But with different constants so it can install side-by-side.)
3. AndyDrive's installer installs AndyDokany. (Which no other Dokany products use.)
4. AndyDrive's uninstaller removes AndyDokany. (Which doesn't impact any other products that use Dokany.)

In this approach, the constants would need to be parameters set as build, so Dokany and AndyDokany use the same source code. (No forking needed.)

(See:)
https://github.com/dokan-dev/dokany/commit/249d4f5248c09c6869212627df389c36cc4a9746
https://github.com/dokan-dev/dokany/blob/master/Dokan.props#L5

**Comment by js69** [comment]
The Dokany drivers should be installed as Permanent package. If you use WiX Burn as your setup program, you can simply use the Dokan .msi file and set that parameter.

Liryna, I think it would be helpful to put the msi file you create up for seperate download as well.

**Comment by andysyncplicity** [comment]
@js69, The problem is that in the hypothetical "AndyDrive" product, it must uninstall cleanly.

This means uninstalling all drivers that it came with, including Dokany.

One way to solve the problem is for AndyDrive to just recompile Dokany as a different product, and completely remove it when it's uninstalled. No need to worry about what other Dokany-based products are installed.

**Comment by marinkobabic** [comment]
The windows has a counter for the installed files if they are shared files. So if the driver was there before you installed your product the counter will be increased. So when you remove your product the driver will remain on the system and the counter will be decreased.

If the driver was installed with your product so the driver will be removed if your product was the only one which uses the driver. It all depends on the counter except you force the remove which will break the other installations.


Von Samsung Mobile gesendet


-------- Ursprüngliche Nachricht --------
Von: Andrew Rondeau
Datum:06.05.2016 21:02 (GMT+01:00)
An: dokan-dev/dokany
Betreff: Re: [dokan-dev/dokany] Facilitate side-by-side installation of many products (#227)


@js69<https://github.com/js69>, The problem is that in the hypothetical "AndyDrive" product, it must uninstall cleanly.

This means uninstalling all drivers that it came with, including Dokany.

One way to solve the problem is for AndyDrive to just recompile Dokany as a different product, and completely remove it when it's uninstalled. No need to worry about what other Dokany-based products are installed.

-

**Comment by andysyncplicity** [comment]
Oh, that makes perfect sense. Thanks!
