### ISSUE TITLE
FUSE - Check if Directory is empty before calling rmdir 

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#270]
Dokan FUSE should list directory fils before try to delete it.
If not empty, rmdir should not be called and STATUS_DIRECTORY_NOT_EMPTY should be returned.

Must be done here:
https://github.com/dokan-dev/dokany/blob/1b5263f04a5c301e82fc3dbeba01cf0e40d187a2/dokan_fuse/src/fusemain.cpp#L171

**Comment by Rondom** [comment]
I actually started on this a long time ago and completely forgot about it.
See the branch https://github.com/Rondom/dokany/tree/fuse-rmdir
I might force-push to that branch, the commit I am talking about right now is 5d7547cd154b8623a1fd4b59bd2d359a368f1235

I do not have time to work on this right now, but maybe someone else can do more testing.

1. Currently it is not really tested very much. It would be nice if people could give it a try with their own FUSE-filesystems. 
2. I noticed that no permission-check is done either. In fact permissions are not really enforced throughout dokan-fuse. So should we do that?
3. The code-path using the older `getdir()` callback instead of the newer `readdir()` is completely untested. Maybe test with an old fuse-mirror?
4. @Liryna As you can see I put the check earlier, which is in line with [what I read about file-deletion on Windows](http://download.microsoft.com/download/4/3/8/43889780-8d45-4b2e-9d3a-c696a890309f/File%20System%20Behavior%20Overview.pdf). This is a general question about Windows: What happens when the deletion fails during cleanup? Is it true that there is no possibility to signal user space that a deletion failed?
5. Is there the possibility of race conditions?
    * FileSetDisposition is called
    * the DeleteDirectory callback enumerates the direntries, finds none
    * a file is placed into the directory
    * DeleteDirectory returns with no-error, signals that the directory is going to be deleted
6. Cleanup of the patch is necessary: removing debug-prints, some code-cleanup and code-style.
