### ISSUE TITLE
Kernel driver INF version info not updated

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#323]
I have not yet looked into this, but for some reason the INF-files that are generated by WDK do not pick up the version from dokan1.sys. The date is adjusted, though.

```
DriverVer=08/25/2016,1.0.0.0
```

The process of putting the version info into the INF seems to be called "stamping". 

https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.0-716/job/th1ioajyxvhoow0h#L711

```
StampInf:
C:\Program Files (x86)\Windows Kits\10\bin\x86\stampinf.exe -d "*" -a "x86" -v "%DOKANVersion%.0" -k "1.9" -f Win32\Win7Release\dokan.inf 
Copying "C:\projects\dokany\sys\dokan.inf" to "Win32\Win7Release\dokan.inf" for stamping
Stamping Win32\Win7Release\dokan.inf [Version] section with DriverVer=08/25/2016,1.0.0.0
Copying file from "Win32\Win7Release\dokan.inf" to "C:\projects\dokany\Win32\Win7Release\dokan.inf".
```

**Comment by Liryna** [comment]
Hi @Rondom ,

The version is taken from https://github.com/dokan-dev/dokany/blob/master/Dokan.props#L6

I just changed it to `<DOKANVersion>1.2.3</DOKANVersion>`, rebuild and get as expected:
`DriverVer=08/25/2016,1.2.3.0`

**Comment by Liryna** [comment]
@Rondom any news from this ?

**Comment by Rondom** [comment]
I have not looked into this and I do not have much time this week.

**Comment by Rondom** [comment]
Version is set in `sys.vcxproj` using multiple instances of

    <TimeStamp>%DOKANVersion%.0</TimeStamp>

I think, the whole system of setting the version numbers can be optimized to have less duplication.
I personally would rather do this properly once and for all at some later point.

As a workaround we can set the last number manually in the commit that is tagged v1.0.0. In the commit following that tagged commit we can set Dokan-version to 1.0.1 or 1.1.0 and set it back to zero (until a proper solution is implemented before the next post-1.0.0-release).

Btw: What will the x in 1.0.0.x be for the final 1.0.0-release?

**Comment by Liryna** [comment]
Currently there is SetAssemblyVersion project that set the version from version.txt in version.xml, rc files and Dokan.props.
Dokan.props defines are use by projects in file name and the TimeStamp for sys.
I tried to reuse Dokan.props defines in rc files but this does not seems to work :cry: sadly...
There is also `DOKAN_MAJOR_API_VERSION` in sys/public.h that should be changed by SetAssemblyVersion (currently need to be done manually). This define has to stay in header because it is used by dokan.dll and external FS.

`<TimeStamp>%DOKANVersion%.0</TimeStamp>`
Can you explain how this is duplicate for you ? This is needed for each build project (win7, win8,...) and one time configured in VS GUI.

>Btw: What will the x in 1.0.0.x be for the final 1.0.0-release?

I think simply 1.0.0.5000, I don't see other possibility :cry:

**Comment by Liryna** [comment]
- [ ] Change `DOKAN_MAJOR_API_VERSION` from sys/public.h with SetAssemblyVersion 
- [ ] Try to reuse Dokan.props defines in rc files

**Comment by Liryna** [comment]
done with https://github.com/dokan-dev/dokany/commit/e1c662491c9eebf418d348e8a813f277e8008556
