### ISSUE TITLE
Win7 - VLC fail to open video

### ISSUE THREAD

**Issue by Liryna** [dokan-dev/dokany#331]
>mirror.exe /r C:\Users /l m /n /u \localhost\myfs /d /s

By the mirror log, when we play the file \\localhost\myfs\liryna\Desktop\video.divx 
VLC try to open C:\Users\liryna\Desktop\myfs\liryna\Desktop\video.divx that fail obviously

It seems like the path is somehow incorrectly converted on the dokan side.

https://github.com/dokan-dev/dokany/blob/master/sys/create.c#L560
should check RelatedFileObject

**Comment by Liryna** [comment]
Windows media player is able to read the video in the dokan mirror \localhost\myfs\video.divx 

VLC is unable to browser the dokan shared folder (file -> open file)

**Comment by Liryna** [comment]
This is a vlc related issue. With a standard shared localhost folder, vlc is not able to read the file and it is the same error that with dokan.

**Comment by gribeiro2401** [comment]
Liryna,

With dokany v1.0.0.4-rc4, I definitely cannot play video files with both vlc and the windows media player on a mirror.exe mounted volume with UNC name. I havent tried with the most recent dokany snapshot but to me, unless this is something that has been fixed after the v1.0.0-rc4, there is a real issue here.
Also, not sure how much this is relevant here, both vlc and the media player can play video files from smb mount points.

Thanks

**Comment by Liryna** [comment]
smb mount points and localhost shared folder are two different things.
Try to share a folder on your desktop and acces it by \\localhost\myfolder, you will see that vlc will not be able to play it too.

**Comment by gribeiro2401** [comment]
Ok. Here is what I did:
1. I shared my c:\Temp folder
2. Mapped \\localhost\Temp to Y:
3. Played a video in Y:\ with vlc and the media player. This works with both players

With mirror:
1. run the command: mirror.exe /r c:\Temp /l z /n /u \\localhost\dokan
2. try to play a video in Z:\. This fails with both the media player and vlc

Is there something wrong in my test?

**Comment by gribeiro2401** [comment]
A couple more things I noticed:
- not sure what this means, but in the vlc media files opening dialog, a mirror mounted volume is shown as disconnected while a locally mounted shared folder is connected (cf attached screenshot: z:\ is disconnected while y:\ is connected)
- also, if I enter explicitly \\localhost\temp\myvideofile.avi as the filename in vlc, it fails like with mirror, but that's ok as no user is going to do that. They are just going to select the file in the mounted volume, which works with a mounted shared folder, but not with mirror.
![capture](https://cloud.githubusercontent.com/assets/22222089/18570381/3bfc0ce0-7b5e-11e6-9627-81775dc13a03.PNG)

**Comment by Maxhy** [comment]
I cannot reproduce your issue (Win 8.1). This is working on my side, I can open video file on mounted drive (with both 1.0.0-RC4 and latest commits). It is indeed failing through \localhost UNC path but this is kind of 'normal' as VLC also failed with this kind of path without Dokan as you both noticed.

**Comment by gribeiro2401** [comment]
I am on win7 x64 sp1.  I have never been able to play video files over a network volume mounted with mirror.exe whatever the player. It only works when it is a local volume.

**Comment by Liryna** [comment]
I have been able to reproduce your issue on win7 but I have not been able to find the reason of it.
The logs do not seems to have a CreateFile failing. It probably come from the kernel.

[log.txt](https://github.com/dokan-dev/dokany/files/476776/log.txt)

This does not happen on win8 & 10

**Comment by gribeiro2401** [comment]
Looks like v1.0.0 went out without a fix for that :-)
I can understand that this issue might not be critical for most Dokan users but it happens to be a blocker for me.
Any idea about when this could be fixed?

**Comment by Liryna** [comment]
Release took me all my time.
Next step on this should be to look at kernel logs to see if some request are denied before reaching user land fs.

**Comment by Kerbox** [comment]
Do anyone else have trouble with VLC now even on a normal mount on windows 7? It's a bit difficult to tell from the logs what is happening, since there is so much activity even when opening a single file.

But I'm seeing CreateFile in mirror with the FILE_FLAG_OPEN_REPARSE_POINT flag set, isn't that weird?

![dokanwin7vlc](https://cloud.githubusercontent.com/assets/356417/19398267/2188c8bc-924c-11e6-97fd-73fd7864ac26.PNG)

**Comment by Liryna** [comment]
Hi @Kerbox ,

I think here we will need to look at the kernel logs (probably also use process monitor https://technet.microsoft.com/en-US/sysinternals/processmonitor.aspx)
And see if there is not  a request refused when it should be accepted.

**Comment by Kerbox** [comment]
Here is the dbgview output at least: [dbgview](https://gist.githubusercontent.com/Kerbox/9029957fd435ded9df10c39102edea3a/raw/3aeb022fdb0d1dbcbb3bd46305ca1fc08ed39957/dbgview.log)

I note that there isn't a DokanCompleteRead in the entire log!

**Comment by Liryna** [comment]
DispatchQueryInformation result = 80000005 is not important.
It is createfile that should be checked.

Bad file descriptor would probably mean that he has not been able to open the file at all.

Process monitor would help to show any error and compare with a normal behavior on NTFS FS.

**Comment by Kerbox** [comment]
Process monitor is showing that ReadFile is failing with INVALID_PARAMETER. I can see a CreateFile for the mp4 file with the Directory option set. [procmon csv](https://gist.githubusercontent.com/Kerbox/9029957fd435ded9df10c39102edea3a/raw/31b9389886674ba107da9421dd80c161b934d365/Logfile.CSV)

I added some extra print outs to the [kernel log](https://gist.githubusercontent.com/Kerbox/9029957fd435ded9df10c39102edea3a/raw/14657da675d6dcb17ea6c48b55d046c5ad7ab66f/dbgview_extra.log).

The problem seems to be that the ReadFile is operating on a file which has the DOKAN_FILE_DIRECTORY bit set.
Help me explain this:
The ReadFile's that fail are operating on the fileObject FFFFFA80024CBC60. The only directory bit related to that is at event 5547, where it is set for the root directory.
There are a few CreateFile for \triforce.mp4\ which is requested with FILE_DIRECTORY_FILE, but this seems to be another fileObject (but is that relevant? Can the fileObject pointer change after create?)

**Comment by Liryna** [comment]
It first open the file normally, read it and after open the file as a directory ? O_O wow

Does the request `\triforce1.mp4\` go to the mirror ? it succeed ? (i don't see it in the procmon logs). This should be fail "normally".
Have you been able to compare with the NTFS FS ? (reproduce on the same file and compare where it should fail/succeed)

About fileObject, I don't really know if the memory value is always the same sorry 😢

**Comment by Kerbox** [comment]
Yes, the request goes to the mirror, but as \triforce1.mp4 (because the last slash is stripped) with the FILE_DIRECTORY_FILE set. This is currently allowed, which changes the FCB of the already opened file handles. I created a pull request with a fix on the mirror side. But maybe there should be some fix in dokan to prevent such a scenario from happening?

Relating to this github issue though, I cannot reproduce it on windows 7 with the latest source.

**Comment by Liryna** [comment]
Fixed with @Kerbox PR https://github.com/dokan-dev/dokany/commit/0cf54fa20387c6b056ff1e71ac183eb5247b9f4b Ty !
