### ISSUE TITLE
cert/dokan-import.ps1 does not work on Windows 7

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#342]
This is a minor nitpick. I am not sure if someone will ever implement this, but this ticket can as well serve as "documentation".

[Import-Certificate](https://technet.microsoft.com/en-us/library/hh848630(v=wps.620).aspx) and [Import-PfxCertificate](https://technet.microsoft.com/en-us/library/hh848625(v=wps.620).aspx) are not available on Windows 7. Upgrading PowerShell does not help, they seem to be part of the OS.

The script should gracefully detect that those Cmdlets are missing and:
1. Try to run CertMgr and error if CertMgr is not available 
2. Give instructions on where to get CertMgr (shipped with VS and with Windows SDK)

**Comment by Rondom** [comment]
Alternative approach using some .Net-code: https://lennytech.wordpress.com/2013/06/18/powershell-install-sp-root-cert-to-trusted-root/

**Comment by Liryna** [comment]
That's right @Rondom I was not even aware of this :O

Alternative does not seems to be what we want :cry: they only show how to make the cert valid for powershell.
The certificat need to be installed in the root store and haven't found something in command line for windows 7 :(

Like you say, this is probably never be faced and it is not much important since it still can be done manually.

**Comment by Liryna** [comment]
@Rondom I think a simple little message as you proposed would be the best and most fast way to do it.

**Comment by Rondom** [comment]
I will look at it in November.

**Comment by Liryna** [comment]
I will add the check myself :smiley: 
you have a break in october ?

**Comment by Liryna** [comment]
Fixed with https://github.com/dokan-dev/dokany/commit/2f16f66548a25934e4a668cc363d3a445e5dbb21
