### ISSUE TITLE
Two AppVeyor accounts fighting over Dokany repo

### ISSUE THREAD

**Issue by Rondom** [dokan-dev/dokany#380]
There seems to be two AppVeyor-accounts linked with this GitHub repository. The GitHub PR will kick off one build at [Maxhy](https://ci.appveyor.com/project/Maxhy/dokany/build/1.0.1-822) and one at [Lyrina](https://ci.appveyor.com/project/Liryna/dokany-lm73i/build/1.0.1-40/job/mamd00r3aelpu317). One of the two builds (the fastest? the slowest?) wins in updating the build-status here at GitHub. In the builds linked above, @Liryna won...

**Comment by Rondom** [comment]
It is enough to remove the permissions in GitHub.

@Lyrina: While you are at it, can you trigger a rebuild of https://ci.appveyor.com/project/Liryna/dokany-lm73i/build/1.0.1-41/job/55fcggmy3iwpbv24, I have been unable to find out, why this suddenly fails.

**Comment by Liryna** [comment]
Oups 😄 This seems to come when we tried to shared access on the appveyor dokany account.
I removed liryna since Maxhy has all the history of build.

I have restart your build on Maxhy 👍 https://ci.appveyor.com/project/Maxhy/dokany/build/job/cmlm77rnihva91e3

Thank you @Rondom for pointing out ❤️ even didn't notice it.
