### ISSUE TITLE
Memory leak when calling CreateFile for nonexistent file

### ISSUE THREAD

**Issue by FixBo** [dokan-dev/dokany#409]
Environment
 * Windows version: 10
 * Processor architecture: x64
 * Dokany version: 1.0.1
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

Small memory leak when opening file or directory that does not exists.

`for /L %%I in (1, 1, 1000000) do @if exist M:\nodir\ exit`
or
`for /L %%I in (1, 1, 1000000) do @copy M:\nofile filecopy>nul 2>&1`
adds about 60Mb to mirror.exe process.

**Comment by Liryna** [comment]
Hi @FixBo ,

Thank you for the report 👍 

Leak has been fixed with https://github.com/dokan-dev/dokany/commit/27ce90e2a9dc42fb3dc2063dc556446cedb4f287

Otherwise it seems like there is a last leak with LookupAccountSid https://github.com/dokan-dev/dokany/blob/1ced4c7431f8486d8d17457bca8945a2a3a38e49/samples/dokan_mirror/mirror.c#L112
I don't see how this can leak so it is probably internal to the function (~4k).

I have tested the Microsoft sample https://support.microsoft.com/en-us/kb/111544 and LookupAccountSid  does also leak.
