### ISSUE TITLE
Windows XP is not supported

### ISSUE THREAD

**Issue by KOLANICH** [dokan-dev/dokany#415]
Hi! Is it very hard to bring this to XP?

**Comment by Maxhy** [comment]
XP is not supported anymore, this system is dropped voluntary.
Dokan code may still be compatible with it but not tested since two years on this platform. You will probably have to change build setup and tools.
Latest  released version supporting XP is the old [0.6.0](https://github.com/dokan-dev/dokany/releases/tag/0.6.0)
