### ISSUE TITLE
When create the same name folder after moved it, the copy file operation failed

### ISSUE THREAD

**Issue by noairman** [dokan-dev/dokany#436]
# Environment
 * Windows version: 10
 * Processor architecture: 64 bit
 * Dokany version: 1.0.2.1000
 * Library type (Dokany/FUSE): dokany/mirror
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Similar to the issue #422 ,#428 ,but not just the exe type file( txt,log,dll,zip,exe.pdf,deb file type)
![error](https://cloud.githubusercontent.com/assets/10110303/22719658/76e0ee84-ede1-11e6-865a-dfc7f1ba9f6c.jpg)

This is how i reproduce the issue:
 1.Create the new folder,named "1",at the root directory;
 2.copy the files "1.txt" in it
 3.move the folder "1" to other place;
 4.create the folder "1" again at the root directory;
5.copy the same file "1.txt" into the "1"

Similar to the issue #422 ,#428 
i will get that error "Could not find this item".
And the FileCount remains high with the STATUS_OBJECT_NAME_COLLISION .But this time it's not only the exe file ,but also other type file( txt,log,dll,zip,exe.pdf,deb file type).But the doc,ini file type is OK.

**This issue only can be reproduced after the move folder operation,but not the delete folder and the cut folder operation**.Maybe the IRP_MJ_CLOSE is not done for the file when it's parent folder is moved.

# Logs
[dokan.log.txt](https://github.com/dokan-dev/dokany/files/759489/dokan.log.txt)

I just tested again with snapshot https://ci.appveyor.com/project/Maxhy/dokany/build/job/0o4m6la7kebpn1w5/artifacts
and got the same issue

**Comment by marinkobabic** [comment]
So let's explain what here happens.

We have the root a folder "test". We also create the folder "1" on the root level. Paste the file "1.txt" into the folder one and move then the folder "1" into the test folder. During the move the file "/1/1.txt" is opened by the system. After the move operation the folder "/1" is renamed to "/test/1" DokanCompleteSetInformation. The problem is that the file "/1/1.txt" remains opened. Now if the user creates a new folder "/1" on the root level and tries to paste the file "1.txt" into that folder, the DokanGetFCB finds the opened "/1/1.txt" and causes the STATUS_OBJECT_NAME_COLLISION issue. An workaround would be inside of the DokanCompleteSetInformation also to rename all the FileNames of cached FCB if needed. From my point of view this would be a hack. There must be a way to tell the system to close the file "/1/1.txt" after the rename of the parent folder is complete.

This fix does not work, but the code should look anyway this way:
```c
      case FileRenameInformation: {
        DokanNotifyReportChange0(fcb, &oldFileName,
            DokanFCBFlagsIsSet(fcb, DOKAN_FILE_DIRECTORY) ?
            FILE_NOTIFY_CHANGE_DIR_NAME : FILE_NOTIFY_CHANGE_FILE_NAME,
                                 FILE_ACTION_RENAMED_OLD_NAME);

        // free old file name
        ExFreePool(oldFileName.Buffer);

        DokanNotifyReportChange(fcb,
            DokanFCBFlagsIsSet(fcb, DOKAN_FILE_DIRECTORY) ?
            FILE_NOTIFY_CHANGE_DIR_NAME : FILE_NOTIFY_CHANGE_FILE_NAME,
                                FILE_ACTION_RENAMED_NEW_NAME);
      } break;
```

**Comment by noairman** [comment]
Hi, @marinkobabic 
  I see,and i will try to find the way to fix that if i can,and thanks for your explanation.

**Comment by marinkobabic** [comment]
@noairman Please can you check the pull request above if it solves your problem?

**Comment by noairman** [comment]
@marinkobabic. This fix correctly the issue 👍
Thanks a lot !
