### ISSUE TITLE
Can't remove dokan1.sys

### ISSUE THREAD

**Issue by ndessenius** [dokan-dev/dokany#441]
While i'm trying to install the last release, it seems that i've got a previous version of Dokan.
I can't uninstall it. Nothing in my apps listing.

I tried to remove dokan1.sys & .dll files but i can't because it's used by another program.
I checked my running services but i can't find anything reporting to dokan.

I'm on W10 64 by the way.
Could you help me?

**Comment by marinkobabic** [comment]
You have been able to remove the dlls but just the sys file not? Because
the sys file is registered as Filesystem driver the service is started
during the boot process. The driver service must be stopped before the file
can be removed.

Manually steps are to remove the service dokan1 from registry and reboot
the machine. After reboot the sys file can be replaced.

Hope this information helps.

Thanks
Marinko

**Comment by ndessenius** [comment]
Thank you, Marinko.
I removed dlls and sys file now. I cleaned registry but after reboot, my system still see some trace about Dokan.
My goal is to install new Keybase's version but i can't because i've got an earlier version installed.

It drives me crazy.

**Comment by Liryna** [comment]
Hi @ndessenius 

@ndessenius can you download https://github.com/dokan-dev/dokany/releases/download/v1.0.2/dokan.zip
In x64/Release, run dokanctl.exe like this with admin rights:
>dokanctl.exe /r d 

Reboot, and try to remode dokan1.sys dll again.

**Comment by Liryna** [comment]
@ndessenius hope this helped, do not hesistate if you any other questions.
