### ISSUE TITLE
Use for file system monitoring?

### ISSUE THREAD

**Issue by cocowalla** [dokan-dev/dokany#472]
I'm wondering if Dokany can be used for file system monitoring, with the idea that it could be a more reliable version of .NET's FileSystemWatcher (which relies on ReadDirectoryChangesW under the hood).

From the readme:

> File operation requests from user programs (e.g., CreateFile, ReadFile, WriteFile, ...) will be sent to the Windows I/O subsystem (runs in kernel mode) which will subsequently forward the requests to the Dokan file system driver (dokan1.sys). By using functions provided by the Dokan user mode library (dokan1.dll), file system applications are able to register callback functions to the file system driver. The file system driver will invoke these callback routines in order to response to the requests it received. The results of the callback routines will be sent back to the user program.

Is it possible to register callbacks for CreateFile, ReadFile, WriteFile etc without actually writing a file system? Or perhaps to write a 'pass through' file system that simply captures file system calls, logs them, then allows them to continue untouched?

**Comment by Rondom** [comment]
Do you know FileSpy and Process Monitor? Do they fulfill your needs?

**Comment by cocowalla** [comment]
I believe you are referring to the FileSpy minifilter driver? It would need a fair amount of changes made to it to allow the required callbacks, and also so it could provide information on which user made the changes. Plus I'd need to take care of signing the driver myself, which I think needs an EV signature these days for Windows 10.

If it's the SysInternals Process Monitor you mean, I don't think that allows other programs to register callbacks.

**Comment by Rondom** [comment]
I see. Somehow missed that you were in need of executing code rather than logging only.

Does the Dokan mirror example suit your needs?

**Comment by cocowalla** [comment]
I'm not sure exactly; it certainly looks like it could at least serve as a base.

Can it monitor existing volumes (that is, without having to create a mirror volume that files must be written to)? I'd want end users not to notice any difference in explorer etc

Also, how do .NET programs communicate with the user mode FS driver? Do you have to use comunication ports like you would with a minifilter  driver?

Are there any signing requirements for the user mode driver, or are these only required for the kernel mode driver?

Sorry for so many questions at once!

**Comment by Rondom** [comment]
I am no expert on Windows Kernel FS-drivers, but for me it sounds like what you technically need is a filter driver, but you (understandably :smile:) do not want this due to the hassle of developing Windows kernel-code and the signing requirements.

The Dokan-Kernel-Mode driver is signed with an EV-Certificate i.e. it can be installed without any problems, even on SecureBoot-enabled systems.

The user-mode file systems do not need any signing. There is a user-space library that talks to the kernel-driver. Dokan creates filesystems that can be mounted as a drive, network drive or directory junction. Thus, the transparency you would like to achieve is probably only possible with a filter-driver. There are bindings for .NET. (see links below). Please note that the .NET Mirror is not as feature-complete as [the C-Mirror](https://github.com/dokan-dev/dokany/wiki/Use%20Mirror%20example).

[Documentation](https://dokan-dev.github.io/dokan-dotnet-doc/html/)
[Code](https://github.com/dokan-dev/dokan-dotnet)

**Comment by cocowalla** [comment]
That's what I thought, seems like a minifilter is my only option!

Thanks for your quick and detailed responses, Dokany looks great and I'm going to be looking hard for an excuse to use it on the 1st suitable project that comes along!
