### ISSUE TITLE
Java support for latest dokanfs

### ISSUE THREAD

**Issue by gsaxena888** [dokan-dev/dokany#514]
I'm a little confused. Is there a java wrapper for latest dokanfs that's stable or still being maintained (ie so that new versions of dokanfs have corresponding java wrappers)? If so, where can I go to get it? Also, is there any performance penalty with using the Java wrapper? (I would think there's none or it's trivially small, eg measured in microseconds). If there's no (current and stable) Java wrapper, would there be interest in updating the existing ones so that they are current and stable?

**Comment by Liryna** [comment]
Hi @gsaxena888 ,

There is Java wrapper but only compatible with version 0.6.0.
https://github.com/dokan-dev/dokan-java
Some people have worked a lot to update it to 1.0.0 and also move to JNA
https://github.com/dokan-dev/dokan-java/pull/7
I have no idea on the current status of it https://github.com/dokan-dev/dokan-java/pull/7#issuecomment-263130143

It would be really great if you are interested to continue the PR. I will let myself available if you have any questions on how dokan work or if you issue on some FS behavior.

There is going to be a speed difference like any wrapper compared to natives. All IO calls will be converted from native to JNA calls. I never made the calculus for the C# wrapper but I would say that you do not see a difference for a normal usage and you would not see it at all if your FS is to manage remote files / encrypted since it is this part that will take biggest time.

I hope I have answered your questions, if you are willing to update the Java Wrapper, do not be afraid of it, I will be there to help you on the mechanism.

**Comment by Rondom** [comment]
Hasn't there also been some implementation based on JNR? I cannot find it. So probably my memor yis blurry and I mistook that PR you are talking about as an implementation based on JNR.

(I have never done any Java interacting with native code so I don't even know about the differences JNA, JNI and JNR and thus do not know about what is the latest and greatest)?

**Comment by gsaxena888** [comment]
Hi, Just got back to this. So I don't think we care whether it's using jna, jni, or jnr, so long it's using latest stalbe dokany version and it works....Do we have such a wrapper? And if so, where could I go to get it? We can probably do some fixing/tweaking if it's not too deep into dokany API stuff (and more focused on Java issues)....

**Comment by Liryna** [comment]
hi @gsaxena888 ,

Here is the most advanced dokany compatible wrapper: https://github.com/dokan-dev/dokan-java/pull/7

**Comment by gsaxena888** [comment]
Cool. Would there be anyone interested in "completing it" :) It'd be a labor of love I'm sure, but we can contribute a little towards it's completion (and of course, all the code would go back into the open source community). What we'd be looking for, ideally, is a Java sample program that mimicks the "mirror" sample program that's provided with Dokan.

**Comment by Rondom** [comment]
> Cool. Would there be anyone interested in "completing it" :)

Well, this is open source software. So if there is someone interested in polishing it, I am sure that person will do it :-) So, I suggest anyone interested in this, to "just" start :smile: (and maybe announce your efforts here and in dokan-dev/dokan-java#7 to prevent duplication of effort.
If there are Dokan-specific questions, I am sure that people here will help you. Don't be afraid to ask!

**Comment by gsaxena888** [comment]
Ok cool. Just to be clear: we'd be happy to make $$ contributions to whoever has enough C++/Dokan/Java experience to polish it up. 

That said, here's a really "dumb" question on my part: what makes creating the Java wrapper tricky? Isn't it just about creating a method wrapper for every C++ API, so it's just a lot of copy/paste? (I've never created a Java wrapper for an external program before, so forgive my complete ignorance of this as well as my ignorance of DokanFS....)

**Comment by Rondom** [comment]
There is nothing too tricky there in my opinion. Thus I do not see why you give the existing code a try and improve it (and hopefully share your improvements).

**Comment by Liryna** [comment]
Java wrapper has now two new maintainer @soywiz and @jhult 🎉 
The wrapper has been a lot improved and I guess they are accepting review and testing !
