### ISSUE TITLE
SetFileSecurity with inheritance

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokany#60]
Hello,
Did anybody else encounter a problem with setting access rules with inheritance on a folder?
I tried to set the following SDDL - O:BAG:BAD:PAI(A;OICI;FA;;;WD)
which means -

    Owner: Administrators
    Group: Administrators
    Rights: Everyone - Full Control
            For all subfolders

When I check the security settings on the folder, I see that they apply only for the current folder.

I tried to check if it works in the Mirror project, but the security tab doesn't show up in the mirrored drive. Probably because it works with the future version of Dokan, and not 0.7.4.

Thanks!

**Comment by Maxhy** [comment]
Fixed with b48fd83ab9297dea600f4cf43a527d63e44d54dd.
The issue was on Dokan driver using FileObject->RelatedFileObject->FileName which is not safe (FileName buffer integrity is not guaranteed outside the associated file object pre-create routine). Fixed by using cached filename from dokan file context.
