### ISSUE TITLE
[Question-ish!] AdjustTokenPrivileges() usage in mirror

### ISSUE THREAD

**Issue by sgraves66** [dokan-dev/dokany#600]
After reading through MSDN, it seems like it's best to remove process-level privileges after whatever friendly, neighborhood call required them in the first place is used. I could see some security implications leaving adjusted privileges throughout the lifespan of the process.

Here is the article that got my curiosity flowing: [GetUserObjectSecurity()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa446675(v=vs.85).aspx)

> To read the system access control list (SACL) from the security descriptor, the calling process must have been granted ACCESS_SYSTEM_SECURITY access when the handle was opened. The correct way to get this access is to enable the SE_SECURITY_NAME privilege in the caller's current token, open the handle for ACCESS_SYSTEM_SECURITY access, and **then disable the privilege**.

Mirror adds the privilege once, so just wanted to know if there was a reason for this that I'm overlooking:
[here](https://github.com/dokan-dev/dokany/blob/84ae0878195fcef9ff60331e0209443ff6228d84/samples/dokan_mirror/mirror.c#L1643).

As an example, this is my modified version of SetFileAttributes() callback:
```
static BOOL AddRemovePrivilege(LPCSTR priv, BOOL add) {
      BOOL ret = FALSE;
      LUID luid;
      if (::LookupPrivilegeValue(0, priv, &luid) || (::GetLastError() == ERROR_SUCCESS)) {
        LUID_AND_ATTRIBUTES attr{};
        attr.Attributes = add ? SE_PRIVILEGE_ENABLED : SE_PRIVILEGE_REMOVED;
        attr.Luid = luid;

        TOKEN_PRIVILEGES priv{};
        priv.PrivilegeCount = 1;
        priv.Privileges[0] = attr;

        HANDLE token = nullptr;
        if (::OpenProcessToken(::GetCurrentProcess(), TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY, &token) || (::GetLastError() == ERROR_SUCCESS)) {
          TOKEN_PRIVILEGES oldPriv;
          DWORD retSize;
          ::AdjustTokenPrivileges(token, FALSE, &priv, sizeof(TOKEN_PRIVILEGES), &oldPriv, &retSize);
          ret = (::GetLastError() == ERROR_SUCCESS);
          ::CloseHandle(token);
        }
      }
      return ret;
    }
```

```
static NTSTATUS DOKAN_CALLBACK Sia_GetFileSecurity(LPCWSTR fileName, PSECURITY_INFORMATION securityInfo, PSECURITY_DESCRIPTOR securityDescriptor, ULONG bufferLen, PULONG lengthNeeded, PDOKAN_FILE_INFO dokanFileInfo) {
      UNREFERENCED_PARAMETER(dokanFileInfo);
      FilePath filePath(GetCacheLocation(), fileName);
      SString siaPath = CSiaApi::FormatToSiaPath(fileName);

      NTSTATUS ret = STATUS_SUCCESS;
      const auto  requestingSaclInfo = ((*securityInfo & SACL_SECURITY_INFORMATION) ||
        (*securityInfo & BACKUP_SECURITY_INFORMATION));

      const auto hasSeSecurityNamePriv = AddRemovePrivilege(SE_SECURITY_NAME, TRUE);
      if (not hasSeSecurityNamePriv) {
        *securityInfo &= ~SACL_SECURITY_INFORMATION;
        *securityInfo &= ~BACKUP_SECURITY_INFORMATION;
      }

      HANDLE handle = ::CreateFile(&filePath[0], READ_CONTROL | ((requestingSaclInfo && hasSeSecurityNamePriv) ? ACCESS_SYSTEM_SECURITY: 0),
        FILE_SHARE_READ,
        nullptr,
        OPEN_EXISTING,
        FILE_FLAG_BACKUP_SEMANTICS,
        nullptr);

      if (not handle || (handle == INVALID_HANDLE_VALUE)) {
        ret = DokanNtStatusFromWin32(::GetLastError());
      }
      else {
        if (not ::GetUserObjectSecurity(handle, securityInfo, securityDescriptor, bufferLen, lengthNeeded)) {
          const auto error = ::GetLastError();
          if (error == ERROR_INSUFFICIENT_BUFFER) {
            ret = STATUS_BUFFER_OVERFLOW;
          } else {
            ret = DokanNtStatusFromWin32(error);
          }
        }

        ::CloseHandle(handle);
        if (ret == STATUS_SUCCESS) {
          *lengthNeeded = ::GetSecurityDescriptorLength(securityDescriptor);
        }
      }

      if (hasSeSecurityNamePriv) {
        AddRemovePrivilege(SE_SECURITY_NAME, FALSE);
      }
        
      return DOKANY_EVENT(__FUNCTION__, ret, siaPath, filePath);
    }
```

I'm tacking on more question on the end here because it's been nagging at me, although unrelated. Curious to know why the additional call is needed:
```
if (ret == STATUS_SUCCESS) {
  *lengthNeeded = ::GetSecurityDescriptorLength(securityDescriptor);
}
```
More specifically, under what scenario would GetUserObjectSecurity() not populate the 'lengthNeeded'? Dokany mirror version [here](https://github.com/dokan-dev/dokany/blob/84ae0878195fcef9ff60331e0209443ff6228d84/samples/dokan_mirror/mirror.c#L1263).

Thanks so much!

**Comment by Rondom** [comment]
Regarding the last question: do a git blame. There has been some bug where the length wouldn't get set in certain situations.

**Comment by yin19941005** [comment]
Hi all,

Let me answer your last question first. 

### Not populate the 'lengthNeeded' question

> More specifically, under what scenario would GetUserObjectSecurity() not populate the 'lengthNeeded'? 

In short, this should be a bug from Microsoft cause by the SMB 2.0 or later version. This is a trial-and-error findings, so, I have no idea why this is happening. (SMB 1.0 will completely works fine)

You may check [the Related with Security Descriptor part of this comment](https://github.com/dokan-dev/dokany/issues/476#issuecomment-293211712) and [this commit](https://github.com/dokan-dev/dokany/issues/476#issuecomment-300729078) for details.

### Quick Review for Handle
[https://en.wikipedia.org/wiki/Handle_(computing)](https://en.wikipedia.org/wiki/Handle_(computing))

> a handle functions as a capacity: it not only identifies an object, but also associates access rights.

This means if you got the handle, you already granted the access rights. That's why I am saying when the caller already got the handle, he/she expects him/her already granted the access rights (in this case, the caller is expecting they already granted access to SACL when `STATUS_SUCCESS` is returned in MirrorCreateFile.).

### AdjustTokenPrivileges issue

For the AdjustTokenPrivileges() issue, I see your point but actually I am doubt should we create the handle in `MirrorGetFileInformation`. 

The AdjustTokenPrivileges will always success because you started the mirror.exe with administrator right (If you are not started with administrator right, you will never success to AdjustTokenPrivileges and be always safe.). But why we are calling to enable the privileges? This is because we want to pass a security check!! However, in the `MirrorGetFileInformation` we are not able to done any security check with the caller. Because you are not able to get the caller access token, this only possible to get in  `IRP_MJ_CREATE` routine functions. This means, by Microsoft design, all the security check should and must done in the `IRP_MJ_CREATE` routine functions. In my opinion, `ERROR_PRIVILEGE_NOT_HELD` or NTSTATUS `STATUS_PRIVILEGE_NOT_HELD` is not expecting by the caller when they already got the handle. Within the `MirrorGetFileInformation` the `CreateFile` function call is just dummy security check and almost forced to pass.

If you enabled the `/p` impersonate caller option added recently, you will a lot of `error code = 1314 (ERROR_PRIVILEGE_NOT_HELD)` and `0xC0000061 (STATUS_PRIVILEGE_NOT_HELD)` returned in MirrorCreateFile. And they will instantly make another MirrorCreateFile call by the same caller with similar flags. And these follow up calls will success and able to perform the following operations. I think this is the case that they  instantly granted `ACCESS_SYSTEM_SECURITY` by `AdjustTokenPrivileges` and make another call. After the operation finished, I believe they will disable the privilege. **In my opinion, this is the case that the `Remarks` in `GetUserObjectSecurity()` described.**

Why I am discussing should we create the handle in `MirrorGetFileInformation`? **Because if the create the handle is not needed, the `AdjustTokenPrivileges()` function call is not needed either.** The only usage for `g_HasSeSecurityPrivilege` is handling the create handle case in `MirrorGetFileInformation`.


<br><br>
Sorry for the poor presentation, I hope you can understand what I am mentioning.

**Comment by sgraves66** [comment]
Perfect! I haven't begun testing around security yet, so this is really great info. I was assuming 'MirrorGetFileInformation' required the 'CreateFile()' call and never checked for an existing handle in the struct. So possibly better to just let it fail and/or require the caller to 'AdjustTokenPrivileges()' as necessary? I can see the benefits of mirror doing this, but in my case the implementation will always be running as user and probably best to leave it up to the process opening the file to do the dirty work.
