### ISSUE TITLE
Thumbs.db & Desktop.ini

### ISSUE THREAD

**Issue by shlatchz** [dokan-dev/dokany#61]
The OS doesn't create those files on a Dokan drive.
Is it because of how the dokan drive is built? Is it the same reason the dokan drive doesn't have a recycle bin?

Thanks!

**Comment by Maxhy** [comment]
Yes this is related to mount manager, see #50. Work in progress, I just need more free time to finish it.

**Comment by suy** [comment]
I don't have old windows versions at hand, but I can assure you that on Windows 8 desktop.ini is attempted to be read (I don't know what could cause it to be written, though). Strangely, even on files that I'm reporting that are not directories (I get odd requests to foo.jpg/desktop.ini).

WRT thumbs.db, according to Wikipedia [since Windows Vista those are centralized](https://en.wikipedia.org/wiki/Windows_thumbnail_cache#Centralized_thumbnail_cache). Again, I can only confirm for W8.

**Comment by shlatchz** [comment]
It's the same with Win7..

**Comment by Maxhy** [comment]
Done with mount manager merge.
