### ISSUE TITLE
Saving/dragging a mail from Outlook crashes Explorer+Outlook+Mirror sample

### ISSUE THREAD

**Issue by 0x4a616e** [dokan-dev/dokany#616]
# Environment
 * Windows version: 10
 * Processor architecture: x64 
 * Dokany version: 1.0.5
 * Library type (Dokany/FUSE): dokany
 
# Check List
  - [X] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [X] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [X] I can always reproduce the issue with the provided description below.
  - [X] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [X] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description

When dragging a mail from Outlook to a dokany folder (or saving to it via the menu), all affected applications crash. As a result, the entire system hangs (no error message or BSOD though) and can only be recovered by a hard reset. The D&D operation is however successful, i.e. after a reboot you can find the mail-file correctly stored at the desired location.

This behaviour seems to be new in 1.0.5.1000 as everything was working well with 1.0.3.1000.

Please let me know if I can provide any more details about the the issue.

# Logs
[log.txt](https://github.com/dokan-dev/dokany/files/1453963/log.txt)

**Comment by Liryna** [comment]
Hi @0x4a616e ,

Does when using the dokan1.dll from 1.0.5 and having dokan1.sys 1.0.3, it work ?

**Comment by 0x4a616e** [comment]
Good guess! I just tried and it worked like a charm.

**Comment by TrabacchinLuigi** [comment]
This looks way more the problem i had!

**Comment by Liryna** [comment]
@0x4a616e @TrabacchinLuigi  Can this be reproduce with another way that using outlook 😃 ?

**Comment by 0x4a616e** [comment]
So far, I haven't found any...

**Comment by TrabacchinLuigi** [comment]
Saving with Revit it happens almost always, it really looks like a deadlock, unfortunately it isn't in the .net part, i can't poit out the line of code, i will download windows SDK and give it a shot but i'm kinda not the c++ developer

**Comment by Liryna** [comment]
@TrabacchinLuigi Just need a way to reproduce the issue simply here :) After will look what is happening ❤️
Can you just describe with Revit how to make it ?

**Comment by TrabacchinLuigi** [comment]
Ok, Revit is an Autodesk software, you can download a trial [Here](https://www.autodesk.it/products/revit-family/free-trial), then to reproduce: 

- Make a new project (we use construction template, but i don't think it's relevant)
- Save it somewhere in dokan (peek a folder because it will create subfolders and files)
- Go to collaborate ribbon tab
- Press collaborate button
- Choose collaborate within your network (this will enable saving madness (behave like a network drive))
- Save again, choose yes at the save as central file prompt (will be prompted only the first time)

if you are lucky enough you'll be immediately stuck, otherwise keep saving

**Comment by pp111** [comment]
Same issue here but saving .doc files with Office 2007. To reproduce it just mount with the mirror example, open a .doc file, change something and save it (It must be .doc since .docx works ok) The mirror application hangs, word hangs, explorer and other applications using the mirrored drive hangs (no error message or BSOD). Finally a reboot is needed.

Going back to version 1.0.4.1000 fixed the issue, so it seems to be some change introduced in 1.0.5.1000

I can provide the mirror logs if you need it.

**Comment by Liryna** [comment]
@TrabacchinLuigi for the guide to reproduce this !
I found the issue and fixed it in the master 👍 

Thanks all of you for the report !
