### ISSUE TITLE
Debug driver is not signed

### ISSUE THREAD

**Issue by TrabacchinLuigi** [dokan-dev/dokany#618]
So... I've got Win SDK and WDK set up, downloaded sources built them, realized i need a signed version, got back here, downloaded the debug version.
I  thought a good reason for it to exist was that it was signed and i could just debug it (not altering the code) but it just won't install (unless i enable not signed driver loading, which lead me back to: i could just buid them then).
I'm doing it wrong ? shouldn't that driver be signed ? if i have to enable unsigned driver loading what's the point of distributing a debug package ?

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

Have you installed the selfsigned certificates on your testing machine ?
https://github.com/dokan-dev/dokany/wiki/Build#signing

**Comment by TrabacchinLuigi** [comment]
Hi @Liryna , yes i mean that package, i got an error saying that the driver could not be installed due to certificate issues... and no i didn't followed that procedure, because i was not planning to build the driver myself, just see where it gets stuck.
Now i've tried to reinstall it to screenshot the message, but it's not shown anymore.
It just won't work saying that i need administrator privileges to install the driver, and if given privileges it still fails saying the driver can't be installed

**Comment by Liryna** [comment]
Are you using windows 10 with last updates ?
This need a sign with EV cert that I do not apply on the Debug build (it takes times). Maybe that's why for your windows it is still not properly signed.

**Comment by TrabacchinLuigi** [comment]
Unfortunately i can't instal the last update because of my shared bootloader 🤕 I've planned a fresh install like months ago ⛑ still no time.
running `dokanctl.exe /r d` and then `dokanctl.exe /i d` i got

```
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
Installing driver...
DokanServiceInstall: Service (Dokan1) installed
DokanServiceControl: Failed to start service (Dokan1). error = 577
DokanServiceInstall: Service (Dokan1) start failed
Driver install failed
```
followed by 
![image](https://user-images.githubusercontent.com/136717/32751811-4e2fbbb6-c8c7-11e7-875f-9e065c682f85.png)

WinVer says i'm running 1607 (not fall creator update) are signing certificate different 😱  ?

**Comment by Liryna** [comment]
>WinVer says i'm running 1607 (not fall creator update) are signing certificate different 😱 ?

Yes this is possible https://github.com/dokan-dev/dokany/issues/271 😢

**Comment by TrabacchinLuigi** [comment]
I'll install the self signed certs, for my purposes, but this is an actual issue on it's own, i'll keep this open, ok ? 👍

**Comment by Liryna** [comment]
@TrabacchinLuigi For you the issue is that the debug installer is not EV signed ?
The debug installer has debug dokan build that are not EV signed because it take a lots of time to do.

**Comment by TrabacchinLuigi** [comment]
I think it is an issue, the solution could be signing them, or just make clear they are not intended for windows higher or equal than 1607 (i think), and enforce building and install self certs instead...
To me the real point is (since  i'm a developer too): have sense having and maintaning this package ? if someone need to debug it probaby will have to build it anyway ... so ... maybe it can be dropped ... just thinking in the business way 🕴

**Comment by Liryna** [comment]
About build:
-Visual studio create his own self signed cert and sign it during the build. This cert can be imported in the VM to make the driver correctly signed for the OS (what I am using every day). Override this cert by another one (real cert) is possible but it is part of the vs user configuration and not the solution. So I could not commit it when I did the test.
-You can use the dokan self signed cert to sign the binary with this script https://github.com/dokan-dev/dokany/blob/master/cert/dokan-sign.ps1 and import the cert in your env with https://github.com/dokan-dev/dokany/blob/master/cert/dokan-import.ps1

Installer:
-During the build installer, it is asked to submit the driver to Microsoft hardware dashboard (EV sign for > 1607).
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/build.bat#L21
This part is manual and needs a special env to be proceeding. It is heavy to run (that's why I only do it for Release installers).
-The debug build installer is here for people who do not want/can to build themselves in debug, who just want the kernel debugging output that exist only in DEBUG (Microsoft Win32 API) without importing self signed cert (and < 1607).

Only thing that can be improved here for me it is to sign for 1607 the debug installer. I would do if it would not take me 2-3h to update all the env, run the test, send to Microsoft, waiting the analyze at each build.

**Comment by marinkobabic** [comment]
Windows has to be set to debugging mode to accept self signed certificates

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/setting-up-local-kernel-debugging-of-a-single-computer-manually

**Comment by Liryna** [comment]
Hi @TrabacchinLuigi ,

I hope we have answer your questions. Otherwise, tell me and I will reopen the ticket.
