### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by pweyzen** [dokan-dev/dokany#654]
I am starting work on trying to integrate dokany support into my application....

1) Is VS 2017 absolutely required?   VS2017 has issues that make it problematic for me to move there.  So, must I use 2017?

2) WDK?  Will the WDK always be a requirement in order to create a dokany application?

**Comment by Liryna** [comment]
@pweyzen Hi,

For building an application around dokany, you do not need vs2017.

You can rebuild the dokan library with your vs and link your application with it. It will work perfectly with the driver installed.

Wdk is only needed to build the kernel driver.

**Comment by pweyzen** [comment]
If I include “dokan.h” – it in turn wants to include ntifs.h

Sounds like I am doing something wrong…

Sent from Mail for Windows 10

**Comment by Liryna** [comment]
@pweyzen Oh, yes thats right. You will need the wdk for it 😢

**Comment by Liryna** [comment]
@pweyzen Or you can load library the dokan1.dll instead of linkind with it. It would need a little of work but there is not so much calls at the end.

**Comment by pweyzen** [comment]
It would go a long way toward the usability of the dokany toolkit if it were able to be used without pulling in the WDK.  

Using the WDK makes it so that I’ll have to get other developers in my group to install, and update build machines, etc…

I know I am not telling you anything new, but making dokany more “plug-in”… would be an awesome feature to anyone that wants to use it.  Now, it’s a bit of a trudge to get the pieces in place.




Sent from Mail for Windows 10

**Comment by Liryna** [comment]
Hi @pweyzen ,

I looked more at the build and the library only need the public.h in sys folder. public.h does not seems to have dependency with wdk header. It was made in such way to not need the wdk but maybe something broke since.
>If I include “dokan.h” – it in turn wants to include ntifs.h

it was the dokan.h of sys folder or library ? if you could be more precise to see if public.h is really wdk dependent.

Just to know, in which language are you planning to build your FS ?
(C# is doing everything with dllimpot so no need to rebuild the library to your VS tool version).

**Comment by pweyzen** [comment]
Hi!

Thanks for putting up with me – getting the wrong dokan.h got me in trouble and made my head spin.
I’ve got the right one in place how, and the world so much more sunny!

My integration is 100% C++ 



Sent from Mail for Windows 10

**Comment by Liryna** [comment]
@pweyzen Perfect ! Thank you for your feedback 👍
