### ISSUE TITLE
IFTest OpLocks group test failure

### ISSUE THREAD

**Issue by shino0729** [dokan-dev/dokany#664]
# Environment
 * Windows version: Windows Server 2012 R2
 * Processor architecture: x64
 * Dokany version: 1.1.0.2000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [ ] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
This issue is same as https://github.com/dokan-dev/dokany/issues/285 which was already closed but I encountered same problem. Is it fixed in the latest version ?

**Comment by Liryna** [comment]
Hi @shino0729,

Oplock has been improved since but there is still some case where it is not fully handled.
See the FStest run on the CI: https://ci.appveyor.com/project/Maxhy/dokany/build/1.1.0-361/job/synasg4f3duvko31#L958
We are looking for some help on this. If anyone could take a look or give a hand, it would be awesome !

Seems like there was no issue opened for it, I rename yours so 👍

**Comment by Liryna** [comment]
IFSTest oplock now pass https://github.com/dokan-dev/dokany/commit/ea6c3fddc2e5e619e12e41c544b297fbc1e335e3
