### ISSUE TITLE
Some performance numbers

### ISSUE THREAD

**Issue by benrubson** [dokan-dev/dokany#670]
Hi,

I did several performance tests to see the impact of Dokany browsing / stating files.

For this I used rsync (the Cygwin version) in dry-run mode (-an), syncing to an empty place a directory containing 10.000 (sub)*directories and 1.000.000 files.
Goal is then to see if Dokany has an impact on the time needed to stat all the files.

I then used some quick lines of Bash in Cygwin to create the files' tree once for all :
```
for j in $(seq 1 200)
do
  mkdir -p /cygdrive/c/my_huge_dir/1/$j
  for k in $(seq 1 50)
  do
    touch /cygdrive/c/my_huge_dir/1/$j/$k
  done
done
echo 1 done
for i in $(seq 2 100)
do
  cp -a /cygdrive/c/my_huge_dir/1 /cygdrive/c/my_huge_dir/$i
  echo $i done
done
```

And then rsync (still from Cygwin) to get performance numbers, several times, for consistency :
`time rsync -an /cygdrive/x/my_huge_dir .`

`noacl,notexec` Cygwin mount options are used for performance purpose.

Solution | Duration
-------- | ---------
Plain files (no Dokany, `cygdrive/c/my_huge_dir`) | 0'50''
Dokany 1.1.0.2 + mirror | 6'20''
Dokany 2-BETA1 + mirror | 5'55''
Dokany 2-BETA1 + fuse-mirror | 5'40''

So sounds like Dokany has quite a noticeable impact on performance browsing / stating files.

Did you know about this performance impact ?
Perhaps there are some greedy code paths ?

Thank you very much 👍 

Ben

**Comment by Liryna** [comment]
@benrubson Hi,

Mirror is expected to be slower since it is on the top of ntfs. Also dokan do not have internal cache in purpose. It is the FS (mirror here) that need to manage it because dokan cannot know if files is remote and has been changed or removed outside for example. 

Otherwise I am impressed to see Dokan v2 slower, by design it should be the same or better.

Do you have possibility to run a cpu analyse with visual studio to see exactly what is taking time for your test?

**Comment by Rondom** [comment]
Don't know about why 2.0 is slower (it should not!). 2.0 is still in development, so there is probably some bug.

The following is mostly hypotheses and when it comes to performance one should always measure, but I can say that there is definitely room for improvement in the following area.

Honestly, I am not surprised that this workload is pretty slow. In general, we could profit from implementing FUSE 3.0 support to speed up listing directories. Also some caching on the kernel side like #291 should help. Problem is that in order to list a directory in Windows, we need more information than readdir alone provides. So we need to stat (getattr) every single file. This should improve the performance of readdir (if a filesystem implements it, encfs very likely cannot without non-portable changes. While it may improve things at least Cygwin-rsync cannot make use of that data, because it uses POSIX file operations which are translated by Cygwin to Windows file operations. So rsync will probably stat every file as well. So I can tell you that there will be at least two stats being done for each file right now -- without any caching...

FUSE 3.0 has [FUSE_READDIR_PLUS](http://libfuse.github.io/doxygen/build-test_2foo_2usr_2local_2include_2fuse3_2fuse_8h.html#af2bcf2a473b41b3cc8da8c079656a074) which allows returning more information on readdir which is cached on Linux. On Windows we can return this information directly without the need of calling stat for each file. Ideally this information would be cached on the kernel side #291 

When used for network-filesystems caching is often problematic, but I do not see why Dokan should not support caching for on-disk-filesystems where no other entity could cause cache coherency issues. @Liryna Do you know how easy it is to enable caching? I expect this to improve the performance for filesystems where modification by other entities is not an issue. There is no need for cache invalidation as long as the cache is optional. I assume it is a bit more than flicking a switch, but given that there are other opensource filesystems such as FastFat, ext2fsd and btrfs-win, it might not be too difficult to find out what needs to be done, right?

**Comment by benrubson** [comment]
Thank you very much Andreas for your detailed answer 👍 

> Problem is that in order to list a directory in Windows, we need more information than readdir alone provides. So we need to stat (getattr) every single file.

You're right, this is at least what encfs4win seems to do redefining `readdir` :
https://github.com/jetwhiz/encfs4win/blob/v1.10.1-RC13/encfs/compatwin.cpp#L752

> This should improve the performance of readdir (if a filesystem implements it, encfs very likely cannot without non-portable changes).

You mean encfs4win would have to rewrite (again) its `readdir` function to get data from the kernel cache ?

> Cygwin-rsync cannot make use of that _(cached)_ data, because it uses POSIX file operations which are translated by Cygwin to Windows file operations. So rsync will probably stat every file as well.

If rsync already stats every file, this means that every file is already stated in the "Plain files (no Dokany)" test above ? So all file stated in about 1 minute (second run) ?
So I'm not sure to understand why a second stat performed by mirror (or encfs) takes an additional 9 minutes (at least).

Many thanks !

**Comment by Liryna** [comment]
@benrubson when you did your test with the mirror, it is the mirror using the fuse wrapper or the dokan wrapper ?
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c

**Comment by benrubson** [comment]
I used the provided mirror, not fuse_mirror (which comes only with Dokany 2).

**Comment by benrubson** [comment]
Btw would it make mirror (or encfs4win) faster being compiled with cygdokanfuse1, when used from Cygwin-rsync ? Or no matter at all ?

**Comment by benrubson** [comment]
I disabled encfs4win `stat` function :
https://github.com/jetwhiz/encfs4win/blob/v1.10.1-RC13/encfs/compatwin.cpp#L632
Well, I made it to return dummy things, without accessing files themselves (so no file operation at all).
It did **not** improve performance at all.
So sounds like overhead may be on Dokany side ?

Btw would it make mirror (or encfs4win) faster being compiled with cygdokanfuse1, when used from Cygwin-rsync ? Or no matter at all ?

**Comment by benrubson** [comment]
To help working on performance improvement, as a test / to give an idea, I disabled encfs4win `stat` :
https://github.com/jetwhiz/encfs4win/blob/v1.10.1-RC13/encfs/compatwin.cpp#L632
Well, I made the function to return dummy things, without accessing files themselves
(so no file operation at all).
It improved performance by around 50% of the overhead.

Btw would it make mirror (or encfs4win) faster being compiled with cygdokanfuse1, when used from Cygwin-rsync ? Or no matter at all ?

**Comment by Liryna** [comment]
Hi @benrubson ,

thank you for updating your numbers, that made me scare not to see improvements for 2.x.x 😄 
I gave an answer on another issue that can maybe be useful for you https://github.com/dokan-dev/dokany/issues/681#issuecomment-381321002

**Comment by benrubson** [comment]
Thank you @Liryna 👍 
Let's then close this, to avoid polluting issues queue. Thank you !
