### ISSUE TITLE
On volume size, without root directory associated. Execution Control & Directly call the functions assigned to the Operations structure.

### ISSUE THREAD

**Issue by zkoria** [dokan-dev/dokany#687]
Hi All,

I am new to the use of dokan, I have some concerns, I appreciate your support to understand them.

Download the library and run the mirror example.

1. "Create a volume for example P: \ without being associated/mirror of a root directory". It is possible to create a file system without having to be a "mirror" of the directory, that is, to create only the e-mail without being associated with a root directory, when trying to understand this and using the mirror example. mirror.exe / l m, mirror to C: \.

2. "The mirror process takes full control of the execution." When tracing the dokan execution, he observed that in "dokan.c" in the WaitForMultipleObjects statement (threadNum, threadIds, TRUE, INFINITE); takes full control and does not allow anything else to run. Is it possible that the mirror example allows me to mount the volume and continue executing other instructions? keeping the volume mounted.

3. "Virtual volume size". The size of the volume displayed by explorer when clicking right-> properties shows 1GB capacity, I execute mirror.exe / r C: \ Users / k 10737418240 / a 65536 -l m with options / k and / a. Is it possible, for example, to create 10 GB of capacity and what would be the way to do it?

4. "Create files, directly call the functions assigned to the Operations structure". As far as I understand, the references to the functions of the operations structure are sent, for example, every time a file is created in the file system. It is possible that I directly invoke MirrorCreateFile MirrorReadFile, etc, that is, that I can directly invoke them to create a new text file directly in the file system, could you ask me what would be the way to do this, since I intend to save files that come from a server, I mean I write them or manipulate them directly in the file system.

Thank you very much.

**Comment by Liryna** [comment]
Hi @zkoria ,

1. You can create a FS that display whatever you want. The mirror goal is to mirror another folder but in C# we have a RegistryFS that displays the registry as FS https://github.com/dokan-dev/dokan-dotnet/blob/master/sample/RegistryFS/Program.cs
Otherwise there are some other projects using dokan if you want more examples: https://dokan-dev.github.io/

2. Currently DokanMain is a sync function but this will be changed in Dokan 2.x.x . For Dokan 1.x.x, you can simply call DokanMain in another thread without problems.

3. Mirror use the default value of the disk size when GetDiskFreeSpace is not implemented. You can see an example of GetDiskFreeSpace here:
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1370
`/a Allocation unit & /k Sector size` are different options that affect file size on the FS but not the FS size.

4. Please see https://dokan-dev.github.io/dokany-doc/html/

**Comment by zkoria** [comment]
Hi @Liryna

Thanks for your fast response!! 
I will review your comments.

**Comment by Liryna** [comment]
Hi @zkoria ,

Can this be closed ?

**Comment by zkoria** [comment]
Hi @Liryna 

2. As you suggested we loaded the mirror example in drive X. In our case, since we are incorporating it into a QT project, we had to remove in the execution thread where we invoked Dokan_Main all the calls to QT elements such as "MessageBox" etc, in addition to raising the thread **between** the instructions QT "**Application app (argc, argv);**" and "**return app.exec () ;**".

![image](https://user-images.githubusercontent.com/39277137/41927678-7d82a668-7938-11e8-92a3-151bcf58324b.png)

3. We first remove the GetDiskFreeSpace comment from the mirror example and from our QT app we obtain the size of the space associated with the account and we pass that value to it, for example:

![image](https://user-images.githubusercontent.com/39277137/41928740-d55fa996-793b-11e8-9cbb-1a7c2e83d75b.png)


However, when adding a file to the drive X the OS responds with notifications of little space on X drive such as:

![image](https://user-images.githubusercontent.com/39277137/41928351-8392ec46-793a-11e8-8af0-e492c1fde044.png)

![image](https://user-images.githubusercontent.com/39277137/41929736-a7a33646-793e-11e8-8f2f-2b7b449e641f.png)

**Do you know why this occurs and how to handle it to handle the low space notification drive X ?.**

Currently we continue testing and integrating the example dokan mirror to our QT app. We have the following concerns:

i. Assuming that the **Dokan_x driver {86,64} .msi** is installed. First. It is possible to reference the dokan library (lib) from the directory where it is installed since we observe that it contains a .lib and .h such directory, example:

![image](https://user-images.githubusercontent.com/39277137/41930561-002ee6a0-7941-11e8-8ddc-dcc3e3369d80.png)

If possible, what is advisable about it?

ii. On QT. 

- Do you have a thread reference or information related to incorporate / include / link the Dokan library to a QT project using CMake (CMakeList.txt)? 

- Do you have any thread reference or information related to incorporating the Dokan Dokan_x driver {86,64} .msi driver into the QT installer framework?

iii. The mirror example indicates that to unmount the drive: _CTRL + C in the console or alternatively via "dokanctl / u MountPoint_ \, there is some way through programming to stop / unmount it, for example we would like that after leaving the QT app we will check the unmount of the drive (X).

Greetings and thanks in advance!.


.

**Comment by Liryna** [comment]
Hi @zkoria 

2. That's the right way to do it 👍 
3. I think here it is probably an issue of parameters set in GetDiskFreeSpace. Be sure to properly provide the correct value to `FreeBytesAvailable, TotalNumberOfBytes ,TotalNumberOfFreeBytes `
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c#L1374-L1376

I.
The installer set different environment variables that can be used like `DokanLibrary1_LibraryPath_x64`
https://github.com/dokan-dev/dokany/blob/master/dokan_wix/Dokan_x64.wxs#L228
Please look at your computer environment for an easy way to see the full list.

II.
There is a Qt project using Dokan. I do not know the state of it but you can probably find something in it 
https://github.com/shi-yan/QtDokanyExamples
Dokan installer is an msi, you should easily find information how to include an msi installer in the QT installer framework.

iii. Please see the documentation about unmount https://dokan-dev.github.io/dokany-doc/html/

I hope this will help you to find the information that you are looking for.

**Comment by hyy829119** [comment]
@zkoria Hi, Have you solved your problem? I have the same problem as you, quota assignment in GetDiskFreeSpace, not even direct assignment, does this quota have to be really big for storage? I have tested it, there is no problem to get the real quota, there is a problem to set the specified quota!

**Comment by Liryna** [comment]
Hi @zkoria ,

I will try to answer all your questions and do not hesitate if I miss one.

II. If you cannot implement GetFileSecurity. It is better to return `STATUS_NOT_IMPLEMENTED`
https://github.com/dokan-dev/dokany/blob/master/dokan/security.c#L156-L162
This will call an internal DefaultGetFileSecurity that will let your user have access to the context menu.

About QT capabilities I will not be able to judge. I know QT but never used in this context. What I can see is that you will have a bottleneck by using a static function whatever context is called.

III. Yes, this seems to be the correct way that you are using to dismount

0. It is alright to open the directory during FindFiles, the mirror is doing the same by calling FindFiles himself. Issues could happen if you keep the handle open too long and have chance to conflict with a CreateFile that request no sharing for example and would fail here regarding the situation.

1.1 Dokan cannot tell you what the purpose of the CreateFile that he is getting from the kernel else that the desired access. He can only provide you the processId that request this createfile.
About analyze behavior of software, they are all different and change often at each version. I don't think it is true science to say "this createfile comes from VLC that will do this because we got this createfile before doing this". 

1.1.i. & 1.1.ii.
Your question seems to be too generic and do you really would like to achieve here ?

1.1.iii. 
2. ThreadCount: https://github.com/dokan-dev/dokany/blob/master/dokan/dokan.h#L106-L107
https://github.com/dokan-dev/dokany/blob/af8ddfc372246b01832ea37924ef513ddc3ed299/dokan/dokan.c#L209-L218
3. Can you link the comment you are talking about ?

**Comment by zkoria** [comment]
Hi @Liryna 

In a version of C # it reads Remove OpenDir now CreateFile:

![image](https://user-images.githubusercontent.com/39277137/46179997-856fc880-c283-11e8-9ec7-a14afb15f004.png)

What would be the way to catch the OpenDir through CreateFile on windows ? (We are using verision C)

Regards!

**Comment by zkoria** [comment]
Hi @Liryna 

To the previous concerns:

2. Thank you. **A. What do you suggest is the ideal value of DokanOptions-> ThreadCount?** Currently we have it to 0, that is to 5.

1.i,ii,iii. 

Currently we want to determine in a unique way when a directory is opened by double click or read by accessed through the command cd. As we explained in the previous post


1.1 We agree with you that it may not be great science, but we still can not determine uniquely when a file is opened. We will try to explain with the following two cases: We need to catch the path of the directory on which we double click and we are doing it with FindFiles only that way we also return the route when we copy and paste a file in the directory, we require uniquely catch the double click on a directory, since every time this happens we send a process, then you can imagine the problem when we are not trapping it in a unique way.

For the case of opening a file the same, we need to uniquely check when a file is open, if we use ReadFiles it is invoked more than once per open file (except for the TXT) which is also a problem for us since Every catch we send a process.

**B. We hope we have made ourselves understood.**

II. Thnaks, we already implemented GetFileSecurity.

**Comment by Liryna** [comment]
Hi @zkoria ,

ThreadCount should be set depending on the computer capacity and needs of the app.

About Directory, please see https://dokan-dev.github.io/dokany-doc/html/ "Dokan File Info Life Time"  -> DOKAN_FILE_INFO.IsDirectory

1.1
Your need is kind of special and I think every solution will be a hack in a way

>if we use ReadFiles it is invoked more than once per open file (except for the TXT) which is also a problem for us since Every catch we send a process.

What if you flag the usage for the first read by process here ? Like that you wouldn't have the invoked for each read.
