### ISSUE TITLE
Read(Write)File and thread safety

### ISSUE THREAD

**Issue by samokhodkin** [dokan-dev/dokany#715]
Hello, guys. 

I'm trying to grasp your a bit too concise description of DOKAN_OPERATIONS.ReadFile regarding thread safety.

>It can be called by different threads at the same time, so the read/context has to be thread safe.

What does it mean anyway?
Should I assume that if a file handle is stored in context, I should expect it to be passed to 2 concurrent calls to the function?

If so, then the ReadFile implementation in mirror.c looks incorrect to me, because it first seeks the handle, then reads it, and does it in a non-atomic way:
https://github.com/dokan-dev/dokany/blob/master/samples/dokan_mirror/mirror.c , line 586 on.
Would 2 threads call it concurrently, the result is unpredictable. 

Someone comment, please.

**Comment by Liryna** [comment]
Hi @samokhodkin ,

This means the read/write operations can happen multiple times at the same moment for the same handle/context. Specially during `OVERLAPPED` read/write
See https://docs.microsoft.com/en-us/windows/desktop/sync/synchronization-and-overlapped-input-and-output

You are right about the mirror. This should be fixed 👍

**Comment by samokhodkin** [comment]
Thank you, Liryna.
BTW, is the asynchronous IO supported? How can we signal the end of the
operation?

**Comment by Liryna** [comment]
Yes, it is supported and there is not need for you to do anything else that usual for asynchronous.
Otherwise ! Had to point that yes it is an issue in the current mirror BUT @Corillian had already fixed it in a PR here: https://github.com/dokan-dev/dokany/tree/Corillian-asyncio
https://github.com/dokan-dev/dokany/blob/Corillian-asyncio/samples/dokan_mirror/mirror.c#L1443

**Comment by luoyouchun** [comment]
Yes. Need a mutex to control.
