### ISSUE TITLE
Please bump DOKAN_VERSION when there is a security fix

### ISSUE THREAD

**Issue by taruti** [dokan-dev/dokany#765]
When there are security issues users of Dokan might want to check that they are running a version with the fix. Currently that is tedious with checking the file versions.

It would be easier if dokan.h DOKAN_VERSION would have been bumped to 121.

Also consider doing this also in future if there security issues.

Bumping DOKAN_DRIVER_VERSION would be even better.

**Comment by Liryna** [comment]
Hi @taruti ,

The `DOKAN_DRIVER_VERSION` should only be updated when there is a breaking change. Otherwise older library would no longer use the driver.
https://github.com/dokan-dev/dokany/blob/6424efd09d8efd5f1ae6622a6b4ef9be27d25153/sys/event.c#L604-L612

But it is right that `DOKAN_VERSION` had to be bumped...
https://github.com/dokan-dev/dokany/blob/a0791e45f1df46f46c0cf6f5ae971d6c3fb9450d/dokan/dokan.h#L58
I will add to the update version script this bump 👍

**Comment by taruti** [comment]
Ok, thanks!
