### ISSUE TITLE
Memory Mapped Reads/Writes

### ISSUE THREAD

**Issue by TonyValenti** [dokan-dev/dokany#773]
Hi All,
I am working on a file system that reads and writes across the internet.  I've run into a few situations that I'm not quite sure how best to handle.

1.  I'm writing to BLOB storage.  Would it be correct that my workflow should look something like this:
On Open: Download blob
On Write: Mark blob as dirty
On Close: If dirty, upload blob.  If error during upload, *what should I do?*

2.  Memory mapped reads/writes
How do I detect these?  It doesn't seem as if there is any kind of FileOpen or FileClose command first so I'm not sure how I will know that the writes are complete.

3.  Does Dokan support async activities?  I'm a .NET developer and it is OK for me to do async tasks inside of the dokan handlers?

**Comment by Liryna** [comment]
Hi @TonyValenti ,

1. I cannot really say since depending on the remote API you have access. The best would be to only check access during the CreateFile, Download wanted blob during read and cache it. During write, upload it and cache the data in case it is read before it is uploaded.

2. On the dokanfileinfo struct param of write function, you have the PagingIo that can give you the information.
Also CreateFile FileOptions will give you some information
https://docs.microsoft.com/en-us/dotnet/api/system.io.fileoptions?redirectedfrom=MSDN&view=netframework-4.7.2

3. You can use async task but each dokan functions need to return with the proper result before the timeout that you can extend with DokanResetTimeout.
