### ISSUE TITLE
Dokany started to fail with Hyper-V

### ISSUE THREAD

**Issue by Temtaime** [dokan-dev/dokany#824]
# Environment
 * Windows version: any
 * Processor architecture: amd64
 * Dokany version: 1.3.0.1000
 * Library type (Dokany/FUSE): Dokany
 
# Check List
  - [x] I checked my issue [doesn't exist yet](https://github.com/dokan-dev/dokany/issues?utf8=%E2%9C%93&q=is%3Aissue)
  - [x] My issue is valid with mirror default sample and not specific to my user-mode driver implementation
  - [x] I can always reproduce the issue with the provided description below.
  - [x] I have updated Dokany to the [latest version](https://github.com/dokan-dev/dokany/releases) and have reboot my computer after.
  - [x] I tested one of the last [snapshot](https://github.com/dokan-dev/dokany/wiki/Build#user-snapshot) from appveyor CI

# Description
Use `mirror /r C:\vms /l N:` and try to create VM with Hyper-V on N: drive.
It will fail with 1.3.0.1000 dokany, but works with 1.2.2.1000.

# Logs
Non-working version sometimes do queries using full paths which fail, e.g.:
CreateFile('\Device\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}\Virtual Hard Disks\MyVM.vhdx', {<null>, False, False, False, False, #4464, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> ObjectNameNotFound
CreateFileProxy : \Device\Volume{d6cc17c5-1735-4085-bce7-964f1e9f5de9}\Virtual Hard Disks\MyVM.vhdx Return : ObjectNameNotFound

With previous version of dokany it uses normal queries.
CreateFile('\Virtual Hard Disks\MyVM.vhdx', {<DokanContext>, False, False, False, False, #4312, False, False}, [ReadAttributes, Synchronize], [ReadWrite, Delete], [Open], [None], [Normal]) -> Success
CreateFileProxy : \Virtual Hard Disks\MyVM.vhdx Return : Success

# Proposed fix
#823

**Comment by Liryna** [comment]
Hi @Temtaime,

Thank you for the report.

#639666b is here to fix https://github.com/dokan-dev/dokany/issues/761
Even if it might have affected the creation of VM, I believe the current is more accurate than previous one. We should fix it and not revert it.

From your log, it just seems the CreateFile fail because a full path is provided and FS implementation does not handle it.
As FileNameInformation currently always return the full path, there is maybe a case where it should not.

We should look at the FileNameInformation query made before this CreateFile.

**Comment by Liryna** [comment]
@Temtaime see https://github.com/dokan-dev/dokany/issues/822#issuecomment-533786550

Can we close this and focus on #822 since both are the same ?

**Comment by Temtaime** [comment]
Ok
