### ISSUE TITLE
Dismounted virtual drive remains on windows Explorer

### ISSUE THREAD

**Issue by alexlozdev** [dokan-dev/dokany#938]
Environment
 * Windows version: Windows10
 * Processor architecture: X64
 * Dokany version: 1.4.0.
 * Library type (Dokany): 
 
When mounting , virtual drive appear well on the windows explorer automatically
But after dismounting, virtual drive keeps to remain on the windows explorer until pressing the key [F5] .
How to disappear virtual drive on the windows explorer when dismounting?

**Comment by Liryna** [comment]
@alexlozdev Hi, 

How are you mounting the drive? We notify explorer that the drive is no longer mounted but depending on how it is started (servicer / rights) the notification will not work.

**Comment by alexlozdev** [comment]
mirror /r E:\test /l M:
dokanctl /u M:

dismounted successfully but virtual drive remains on windows explorer.

I did it Ctrl+C on Console but result is same

**Comment by Liryna** [comment]
@alexlozdev This function is called and should refresh explorer.
https://github.com/dokan-dev/dokany/blob/f7161d7f760f8bf3597c0597066192363b4d470c/dokan/mount.c#L507-L548
This is working on my Win10 so there must be something special on your environment.

**Comment by alexlozdev** [comment]
E:\dokany-master\Win32\Debug>dokanctl /u M:
Driver path: 'C:\Windows\system32\drivers\dokan1.sys'
send global release for M:
Unmount status = 0

I think DokanBroadcastLink , this function was executed successfully, but virtual drive still remain on windows explorer.

but I can see veracrypt works well to disappear virtual drive on windows explorer when dismounting

**Comment by Liryna** [comment]
@alexlozdev I already seen such behavior à long time ago but we fixed the different api calls normally in this function. I do not have another recommendations than looking yourself if you can and see if anything looks to be wrong in your case.

**Comment by alexlozdev** [comment]
Thanks

**Comment by Liryna** [comment]
Hi @alexlozdev ,

Have you been able to get more information on the issue ?

**Comment by jon-blum** [comment]
I have seen similar issues on both mount and unmount.  They only started occurring when I upgraded my Windows 10 machines from build 1909 to 2004 (I haven't yet upgraded to the 20H2 release).

When mounting a drive, any existing File Explorer windows do not update to show the mounted drive in the left-hand pane, but a new File Explorer window does show it.  The reverse happens on unmount.

The error occurs using EncFS4win 1.10 with Dokany 1.3.3.  Upgrading to Dokany 1.4.0 does not fix the issue.

Could you clarify the "servicer / rights" issue you mentioned above?  If EncFS4win is setting up Dokan incorrectly, I may be able to fix that.

If it will help, I will test shortly using mirror / dokanctl to see if it occurs outside of EncFS4win.

**Comment by jon-blum** [comment]
I have seen similar issues on both mount and unmount.  They only started occurring when I upgraded my Windows 10 machines from build 1909 to 2004 (I haven't yet upgraded to the 20H2 release).

When mounting a drive, any existing File Explorer windows do not update to show the mounted drive in the left-hand pane, but a new File Explorer window does show it.  The reverse happens on unmount.

The error occurs using EncFS4win 1.10 with Dokany 1.3.3.  Upgrading to Dokany 1.4.0 does not fix the issue.

Could you clarify the "servicer / rights" issue you mentioned above?  If EncFS4win is setting up Dokan incorrectly, I may be able to fix that.

If it will help, I will test shortly using mirror / dokanctl to see if it occurs outside of EncFS4win.

**Comment by Liryna** [comment]
If service is used to mount the drive it needs the `allow services to interact with desktop` enabled otherwise functions like `SHChangeNotify` will not be able to notify other apps.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/f5f43862-e115-4cfd-94fc-2b7cc5ede2fb/using-shchangenotify-api-through-windows-services-application?forum=vclanguage
This service option is being limited in "newer" Windows version https://www.coretechnologies.com/blog/windows-services/interact-with-desktop/
If I remember correctly, `BroadcastSystemMessage` has a similar requirement. See`BSM_ALLDESKTOPS` (it is used on mount but not umount for us).

Side note, I believe using the mount manager option (`/o` on mirror) do not have this issue. Could you give a try ?

**Comment by jon-blum** [comment]
Hi Liryna -- I will test using mirror tomorrow (Australian time).  And the link you gave to SHChangeNotify suggests another way I can fix the problem -- I can easily modify the EncFS4win source code to call SHChangeNotify on mount / unmount, since EncFS4win runs as the same user as File Explorer.  That may be a useful workaround -- thanks!

**Comment by Liryna** [comment]
@jon-blum EncFS is using the dokan library that does already call those functions (I gave the location in one of my previous answer here) so you shouldn't have to do it.

**Comment by jon-blum** [comment]
Just to confirm -- I used mirror / dokanctl and saw the same issue as alexlozdev did:  the drive showed up on mount, but didn't disappear on unmount.

Adding /o to the command line -- mirror /r E:\test /o /l M: -- made no difference.

Just to confirm, the DokanBroadcastLink function you mentioned is within the Dokan *service*, is that right?  Which runs as a separate user from a calling program like EncFS4win, am I correct? In which case calling SHChangeNotify from EncFS4win, which runs as the ordinary user with admin privileges, could have different results under the new restrictions...

**Comment by jon-blum** [comment]
Further update:  by adding the SHChangeNotify functions to the EncFS4win source code, I seem to have fixed the problem!  Presumably because EncFS4win doesn't run as a service while Dokan does.  So you can just add this to your knowledge base (and possibly to your mirror code).

**Comment by Liryna** [comment]
@jon-blum That's the thing, dokan does not run as a service. Dokan is just a library user by EncFS. This call should already be made. So adding one just means you notify two time explorer on a new drive.


Could you debug/compare your SHChangeNotify and the one from dokan to see if there is any difference ?

**Comment by jon-blum** [comment]
Here's my unmount call:

	SHChangeNotify(SHCNE_DRIVEREMOVED, SHCNF_PATH,
		(LPCVOID)arg->mountPoint.c_str(), NULL);

So it looks like it should be the same as your call...  assuming that mountPoint is a std::wstring rather than a std::string.  I'm not sure why it would be working now, in that case.

I'll get back to you soon once one of our testers does a clean install using our tweaked EncFS package, just to make absolutely sure what we see on a clean machine!

**Comment by Liryna** [comment]
`DokanRemoveMountPoint` or `DokanRemoveMountPointEx` should be used by EncFS4win to get the notification done on unmount.
https://github.com/dokan-dev/dokany/blob/f7161d7f760f8bf3597c0597066192363b4d470c/dokan/mount.c#L599-L601

Just doing a search on EncFS4win Github repository, it does not seems to be the case. Maybe just adding this call in the "unmount process" fix the issue.

**Comment by jon-blum** [comment]
Finally got a chance to return to this problem... EncFS4win uses a FUSE
emulation library called dokan_fuse, which calls DokanRemoveMountPoint as
part of its fuse_unmount function.  This appears to be being called
successfully on my dev machine, and I'm not seeing the error there.  I'm
trying to determine whether other machines which show the error are failing
to make the fuse_unmount call for some reason (in which case it's an
EncFS4win problem), or whether they're calling it and it's still not
removing the mountpoint (in which case it might be a Dokan problem).  Stay
tuned...

--jon

**Comment by Liryna** [comment]
Hi @jon-blum ,

Just a kind ping knowing if you are still on this.

**Comment by jon-blum** [comment]
OK, I've got some leads on what could be going on here, though it's mostly
on our back-burner.

ResolvedDokanRemoveMountPoint is definitely being called by our modified
EncFS through dokanfuse1.

But it turns out that the modified EncFS we've been using also has
modifications to dokanfuse1.dll -- nothing that relates to mounting and
unmounting, though (it's a patch to read and write Windows security
settings).  I hadn't spotted that our installer was quietly substituting
its own dokanfuse1.dll, with an apparent version of 1.0.3.1000, and when it
creates dokanOptions on init the ->Version field is set to 100.

If this is forcing the dokan1.sys and .dll to act like version 1.0 rather
than 1.3 or greater, could this relate to the notification not being sent?
Have there been any changes in the notification code since v1.0, which
setting the ->Version field could be bypassing?

(Note that at this point, the notification clearly gets through on my
development machine, but not on other machines.  Still not sure why.  And
just to confirm, this is only happening on *unmount* now rather than mount.)

--jon

**Comment by Liryna** [comment]
The version was move from `100` to `110` at the version `1.2.0.1000` but this is not related to notification from what I can say. Only an API change for the https://github.com/dokan-dev/dokany/commit/0da77870161c101d3133fd76938951c200f12868 Create flag convertions.

**Comment by Liryna** [comment]
@jon-blum Any news on that ?

**Comment by Liryna** [comment]
I am closing this since I believe it is an environment issue. If new information comes helping to find and analyse the issue, please do not hesitate.

**Comment by jon-blum** [comment]
Quick update -- we were able to work around the issue by generating the
notifications in both our main executable *and* its associated rightclick
handler (which as an Explorer plugin presumably is less likely to be
blocked by Explorer).  So we can leave it at that!

--jon
