### ISSUE TITLE
Problem uninstalling 1.2.1.1000

### ISSUE THREAD

**Issue by filo4u** [dokan-dev/dokany#940]
# Environment
 * Windows version: Windows Server 2019 version 1809
 * Processor architecture: x64
 * Dokany version: 1.2.1.1000
 * Library type (Dokany/FUSE): Dokany

# Description
I've been trying to update to the latest version, but I can't uninstall 1.2.1.1000. I appreciate any help you can provide.

# Logs
[Dokan_Library_1.2.1.1000_Bundle_20201107174626.log](https://github.com/dokan-dev/dokany/files/5505754/Dokan_Library_1.2.1.1000_Bundle_20201107174626.log)
![Dokan Library Uninstall Error](https://user-images.githubusercontent.com/20917155/98455200-6b6f6800-2122-11eb-96f3-6ba80ac736dc.PNG)

**Comment by Liryna** [comment]
@filo4u [3758:3478][2020-11-07T17:47:15]w209: Plan skipped removal of provider key: {5F030BFA-CE6E-408A-9694-F593B319DBBE} because it is registered to a different bundle: (null)
[3758:3478][2020-11-07T17:47:15]w208: Plan disabled rollback for package: Dokan_x64.msi, due to incomplete cache: None, original rollback action: Install
[3758:3478][2020-11-07T17:47:15]i000: Setting string variable 'WixBundleLog_Dokan_x64.msi' to value 'C:\Users\ADMINI~1\AppData\Local\Temp\Dokan_Library_1.2.1.1000_Bundle_20201107174626_000_Dokan_x64.msi.log'

**Comment by Liryna** [comment]
@filo4u Could you take a look at those log file ? Is it possible that you have another app that just installed the dokan msi? without using the bundle

**Comment by Liryna** [comment]
@filo4u let me know when you will be able to provide the informations
